### ISSUE TITLE
Replace bbolt DB usage in tests with an in-memory implementation

### ISSUE THREAD

**Issue by seejdev** [kolide/launcher#1016]
This has been discussed before.... our tests can be flakey and there is great concern that bbolt is a culprit involved.

Enabling our tests to avoid having to use a concrete bbolt implementation, and instead use an in-memory one would:

- Presumably speed up those tests, since the memory operations will be much faster than disk access
- Should improve performance within Github CI, since disk access is a bottleneck and can cause jobs to timeout unpredictably

The sequence here would be:

- [ ] Create an in-memory key-value store implementation
- [ ] Consolidate as much bbolt implementation code into a single key-value store implementation
- [ ] Replace non osquery/extension.go `*bbolt.DB` references with [key-value interfaces](https://github.com/kolide/launcher/blob/main/pkg/agent/keyvalue_store.go) 
- [ ] Replace osquery/extension.go (including launcher tables) `*bbolt.DB` references with key-value interfaces
- [ ] Make tests instantiate and use the in-memory implementation, replacing the `*bbolt.DB` usage

**Comment by directionless** [comment]
Sadly, bolt db doesn't support this. https://github.com/etcd-io/bbolt/issues/227 is the usual thread about it

**Comment by directionless** [comment]
Don't need this issue.
