### ISSUE TITLE
Wire up new icons

### ISSUE THREAD

**Issue by seejdev** [kolide/launcher#1027]
Integrate the icons available here https://github.com/kolide/launcher/tree/main/ee/ui/assets so that systray can use them, and k2 can define menus with these icons.

**Comment by directionless** [comment]
Some rambling thoughts / questions

1. I didn't add the developer/working icon to `ui/assets`, we probably should.
2. Which leads to an interesting question. ui/assets declares constants based on the icon name. But that's probably _not_ what we want to expose, I expect K2 to set things like `default` or `circle-x`, and then we need logic to get from that to the appropriate light/dark/developer icon. Not totally sure where that logic should live.
3. I wonder if there's a way to overlay things to the developer/working icon.
