### ISSUE TITLE
Menu bar icons need to detect dark/light mode

### ISSUE THREAD

**Issue by seejdev** [kolide/launcher#1028]
Building off #1027 , the menu icon code needs to be updated to allow:

1. Callers can specify an icon, and the menu code can intelligently choose dark or light mode based on the OS setting

Need code to monitor and react to dark/light mode changes and update the icons appropriately.

**Comment by directionless** [comment]
> A stretch goal, but not strictly necessary, would be adding code to monitor and react to dark/light mode changes and update the icons appropriately.

I'm assuming we'll need this

**Comment by directionless** [comment]
This shipped
