### ISSUE TITLE
Launcher can create two desktop processes after macOS software update

### ISSUE THREAD

**Issue by seejdev** [kolide/launcher#1034]
This has been observed at least twice, and the common thread was launcher running immediately after a macOS upgrade.

### Symptoms

Two desktop processes

```
    0   953   769   0 10:20AM ??         0:00.46 /usr/local/kolide-k2/bin/launcher-updates/1676352633/Kolide.app/Contents/MacOS/launcher desktop
    0  1127   769   0 10:20AM ??         0:00.50 /usr/local/kolide-k2/bin/launcher-updates/1676352633/Kolide.app/Contents/MacOS/launcher desktop
```

Two systray icons, potentially using different themes, light and dark:

<img width="329" alt="image" src="https://user-images.githubusercontent.com/6288305/218785160-6c42f268-c808-4724-b2e6-8dfb57c38d74.png">

Two launcher user dirs created:

```
drwx------    3 cj             wheel        96 Feb 14 10:20 desktop_501
drwx------    3 _windowserver  wheel        96 Feb 14 10:20 desktop_88
```

**Comment by James-Pickett** [comment]
On possible fix is to make sure UID is > 500 before spawning desktop process. On MacOS, human users start at 501
