### ISSUE TITLE
Adjust check for graphical session for Linux

### ISSUE THREAD

**Issue by RebeccaMahany** [kolide/launcher#1046]
In https://github.com/kolide/launcher/blob/main/ee/consoleuser/consoleuser_linux.go we currently check whether the session is graphical by checking the `Seat` value from `loginctl list-sessions`. However, when I connect to a test VM via RDP, I am not granted a seat and launcher would not spawn a desktop process for me.

It looks like it might be most appropriate to check for `loginctl show-session <session> --value --property=Type` -- if it's x11 or wayland, then it's a graphical session. The `Display` property seemed promising but ultimately doesn't seem to be a good choice on its own -- when @James-Pickett tested on his Linux laptop, the `Display` property wasn't set.

**Comment by directionless** [comment]
I think got fixed. Feel free to re-open if not
