### ISSUE TITLE
Table Request: macOS installed packages and boms

### ISSUE THREAD

**Issue by directionless** [kolide/launcher#1057]
Somewhat related to #1056, it would be very powerful to be able to:
1. Enumerate the `pkg` packages installed on a mac
2. And what their contents are

I'm not totally sure what's possible here.
* `/Library/Receipts/InstallHistory.plist` has a record of a lot of things. We can probably pull some data out of there. 
* `/Library/Receipts` has a bunch of plist and bom files. The plist ones probably have metadata about what was installed, and the boms probably list package contents. 
* Reading bom files unclear. though there's some prior art in https://github.com/iineva/bom/blob/main/pkg/bom/bom.go

I'm imagining a couple of tables. Likely with some input options to avoid returning megs and megs of data.

**Comment by directionless** [comment]
Though I started down this path, trying to find git installs for a customer. I didn't find them. See
* https://k2.kolide.com/3851/live_query/campaigns/12832
* https://k2.kolide.com/3851/live_query/campaigns/12833

**Comment by James-Pickett** [comment]
osquery already contains these tables on macos:

package_bom
package_install_history
package_receipts

**Comment by directionless** [comment]
I don't think we're doing anything here. We can always pick up if we want
