### ISSUE TITLE
Add menu support for relative dates

### ISSUE THREAD

**Issue by directionless** [kolide/launcher#1072]
Discussion with K2, is that we often want to display dates as "in 3 days" and other sorts of relative display.

Is this something we can support? Are there other things we might want to format client side? Does this fit inside go templates, or do we want something else?

**Comment by seejdev** [comment]
This looks helpful https://github.com/xeonx/timeago

**Comment by directionless** [comment]
One of the things I'm least sure about, is how we handle supporting relative dates, vs not. And tinkering a bit with templates, I think we have some really interesting rope. Templates aren't really typed -- if there's an if statement, the untaken branch can have unreferenced functions. eg, this works:
```golang
	t, err := template.New("").Parse("{{if false}}{{.doesnotexist}}{{else}}You have a task named \"{{ .Name}}\"{{end}}")
```

I think this gives us some really interesting rope, in that we can conditionally change behavior based on launcher versions. Though maybe we should make a custom function to expose capabilities.
