### ISSUE TITLE
We should have a menu action for requesting a recheck

### ISSUE THREAD

**Issue by directionless** [kolide/launcher#1093]
As we work with Desktop, it becomes clear that we want the ability to trigger a check refresh. 

Thinking for a minute, I see two ways. 

The _less_ preferable one would be to do something like #1030. Run the queries directly, and some some logs. But this feels somewhat weird.

I think it would be more powerful if we could figure out how to send a message back to k2, that the user would like some action taken. Not totally sure what that looks like, or what channel it runs over.

**Comment by directionless** [comment]
If we want to get to really interesting questions, I think it would be interest to think about how to send questions to desktop, and send the answers back to k2. Sending a "request for recheck" is basically the same

**Comment by James-Pickett** [comment]
could K2 generate one time / ephemeral link that launcher could use to send an http request?

**Comment by directionless** [comment]
This was completed in https://github.com/kolide/launcher/pull/1571
