### ISSUE TITLE
Current production release points to a commit not in main

### ISSUE THREAD

**Issue by erikng** [kolide/launcher#1106]
https://github.com/kolide/launcher/releases/tag/v0.13.6 points to a commit in [disable-control-server-patch](https://github.com/kolide/launcher/compare/disable-control-server-patch) branch which is both ahead and behind `main`.

Could you fix this and point v0.13.6 to the proper commit? 

There's also confusion on my part because https://github.com/kolide/launcher/commit/0bd52cf508bd0e025fdae3552f4e92eed2cf3f15 lands the disabling and then right after  it is reverted https://github.com/kolide/launcher/commit/cd9889695abbec0cbdcc8e3b683137f304c87c1a

Are both v0.13.6 and v0.13.5 bad builds?

**Comment by directionless** [comment]
`v0.13.6` was not a bad build, but it was a hotfix to v0.13.5. As such, if never landed on main. (It might have been more clear as v0.13.5.1, but it's in the past.)

https://github.com/kolide/launcher/commit/0bd52cf508bd0e025fdae3552f4e92eed2cf3f15 disabled something that wasn't quite ready to go live, and had a hardcoded localhost url. Thus it was reverted.

In any event current stable is `v1.0.3`.

**Comment by erikng** [comment]
Then why is it marked as pre-release?

**Comment by directionless** [comment]
I hadn't clicked that button. It's been clicked.
