### ISSUE TITLE
Table request: `softwareupdate` wrapper

### ISSUE THREAD

**Issue by directionless** [kolide/launcher#1122]
With our continued search for more accurate software update information, I think we should add an exec table over `softwareupdate --list`. It should default to using `--no-scan`, it might be neat to support omitting that (which would trigger a network scan), but I don't think the existing exec helpers make that easy. (similarly, there's a bunch of options around `products` that I can't figure out). Ultimately though, I think starting simple. 

I have a smattering of output to build an [`execparser`](https://github.com/kolide/launcher/tree/main/pkg/osquery/tables/execparsers). See https://github.com/directionless/launcher/tree/seph/softwareupdate/pkg/osquery/tables/execparsers/softwareupdate/test-data

**Comment by directionless** [comment]
I am expecting this to be an execparser, and 1 line of diff to https://github.com/kolide/launcher/blob/main/pkg/osquery/table/platform_tables_darwin.go We don't need a full table for it

**Comment by RebeccaMahany** [comment]
Added in https://github.com/kolide/launcher/issues/1122
