### ISSUE TITLE
Expand crowdstrike table to be cross platform

### ISSUE THREAD

**Issue by directionless** [kolide/launcher#1125]
We had a customer request to make some cross platform crowdstrike tables. a smattering of info:
* https://github.com/kolide/launcher/pull/903
* [Internal Slack Discussion](https://kolide.slack.com/archives/CGFJY1SP2/p1681310360960999)
* https://github.com/bdemetris/osquery-crowdstrike-ext

**Comment by RebeccaMahany** [comment]
### Check installed version

#### macOS

```
SELECT * FROM kolide_falconctl_stats WHERE fullkey = "agent_info/version"
```

#### Linux

```
SELECT * FROM kolide_falconctl_options WHERE options = "--version"
```

#### Windows

```
SELECT * FROM kolide_wmi WHERE class = "win32_product" AND properties = "version"` AND whereclause = "name='CrowdStrike Sensor Platform'"
```

### Check paired to tenant

Compare against expected customer ID.

#### macOS

```
SELECT * FROM kolide_falconctl_stats WHERE fullkey = "agent_info/customerID"
```

#### Linux

```
SELECT * FROM kolide_falconctl_options WHERE options = "--cid"
```

#### Windows

```
SELECT * FROM registry WHERE path = 'HKEY_LOCAL_MACHINE\SYSTEM\CrowdStrike\{9b03c1d9-3138-44ed-9fae-d9f4c034b88d}\{16e0423f-7058-48c9-a204-725362b67639}\Default\CU'
```

### Check operational

#### macOS

```
SELECT * FROM kolide_falconctl_stats WHERE fullkey = "agent_info/sensor_operational
```

#### Linux

```
SELECT sub_state, load_state, active_state FROM systemd_units WHERE id = "falcon-sensor.service"
```

#### Windows

```
SELECT status FROM services WHERE name = 'CSFalconService';
```

**Comment by directionless** [comment]
Hrm. Yuck.

- So on macos, `kolide_falconctl_stats` parses `falconctl stats -p`
- On linux, `kolide_falconctl_options` calls `falconctl` with whatever options flags are specificied
- on windows, you can use the registry

I don’t like that we have different patterns for the platforms, but remembering writing these, I think the `falconctl` itself is super different on all three. So I don’t think we _can_ have the same approach. 

I see no reason to name the tables the same thing, if they’re totally different under the hood. So until we're hear about upstream changes, I guess there's isn't actionable today.
