### ISSUE TITLE
Confusion around installing a new MSI over an old install (windows)

### ISSUE THREAD

**Issue by directionless** [kolide/launcher#1139]
We had a report from a customer that running the 1.0.7 MSI over an existing 1.0.3 install didn't upgrade it, and instead resulted in a confusing Repair screen. (Note that this screenshot is somewhat truncated, and we do not know what is below the fold)

![image (1)](https://user-images.githubusercontent.com/179542/232774679-57e6670f-3965-4932-84d7-ad5a478d0839.png)

We should reproduce this internally and see what happens

**Comment by RebeccaMahany** [comment]
I wasn't able to reproduce this over several attempts yesterday and the day before. Based on how the installer works, this screen should only appear when that particular installer has already been run. I think we are safe to close this issue.
