### ISSUE TITLE
Agent is slow to start on windows

### ISSUE THREAD

**Issue by directionless** [kolide/launcher#1140]
@RebeccaMahany was commenting that the Agent felt slow to start on windows, and we saw a similar complaint from a customer. 

This is probably because we set [`DelayedAutoStart`(https://github.com/kolide/launcher/blob/25c0c352ed9963f67b554f0c685682f736b80cdd/pkg/packagekit/package_wix.go#L123)] in our MSI.  This was introduced in https://github.com/kolide/launcher/pull/568 as an attempt to ensure launcher starts _after_ the network services. 

There are likely better solutions. Perhaps something with `LoadOrderGroup` or just better retry logic inside launcher.

**Comment by RebeccaMahany** [comment]
The motivation for fixing this is that when a user reboots and then tries to access an app behind Kolide, if they make it to Kolide verification before launcher starts up, they will be prompted to download the agent. This is a confusing user experience, and it's not that hard to end up in this state -- I've run into this a couple times without trying.
