### ISSUE TITLE
Can we accelerate the agent on menu interaction?

### ISSUE THREAD

**Issue by directionless** [kolide/launcher#1141]
Looking at how users work with the the menu, it feels a little bit like _most_ times the user is interacting with the menu. we're going to want to accelerate the control interval. 

I'm not sure if that's all interactions, or maybe just interactions that trigger an action. Or maybe we need it as a boolean on menu items passed in from K2.

**Comment by James-Pickett** [comment]
Acceleration of the fetching of the control server data is handled in launcher root. All the interaction between the user and the desktop app is handled by the desktop subprocess. We'll need away for the subprocess to communicate the user interaction back to launcher root. We already have some plumbing in place for this with the [desktop runner monitor server](https://github.com/kolide/launcher/blob/main/ee/desktop/runner/monitor_server.go) which provides the desktop subsystem an endpoint to make sure launcher root is healthy. We could repurpose / expand this to let launcher root know when a user is interacting with the menu.

Regarding what "interaction with the menu" means, out of the box the only means we have of capturing the user interaction is from OnClicked listeners than can be applied to all items except the very top level stats bar item. We could:
* anytime anything (other than the top level status bar items) is clicked, we start acceleration
* created a dedicated "refresh" button
* allow k2 to add a specific property to the menu data to specify acceleration on click
