### ISSUE TITLE
Multiple desktops appearing occasionally 

### ISSUE THREAD

**Issue by James-Pickett** [kolide/launcher#1155]
We have received reports of multiple desktops (systrays) showing up.

To help prevent and diagnose this here are some possible improvements:

* Add the `pid` field to all logs associated with a desktop process. This should make it easier to trace through large log files.
* Ensure that when desktop runner declares a desktop process as unresponsive, it is also rejected by the "monitor_server". If for some reason desktop runner is unable to kill the process, the process should terminate it self if it doesn't get a response from the monitor server.

**Comment by directionless** [comment]
I would also suggest that if desktop sees it's parent pid is 1, that it considers itself an orphan and exists.
