### ISSUE TITLE
I want to be able to accelerate control updates, from the control updates

### ISSUE THREAD

**Issue by directionless** [kolide/launcher#1199]
Today, launcher polls for control data on a given interval. And we have this idea of `SetControlRequestIntervalOverride`. One place we use that in #1159.

I'd like to be able to set it in the control data directly. 

Something like:
- t0: launcher pulls control data
- t60: launcher pulls control data, including an interval override
- t65: launcher pull control data
- etc

There's some chance we have this, but I'm not sure I see this plumbed.

**Comment by James-Pickett** [comment]
closed with https://github.com/kolide/launcher/pull/1250
