### ISSUE TITLE
[Question] table.ext

### ISSUE THREAD

**Issue by celevra** [kolide/launcher#1221]
Hi,

https://www.kolide.com/blog/how-to-run-osqueryi-with-kolide-launcher-tables
is a little bit outdated ;-)
how to get just the *.ext ?

regards

**Comment by directionless** [comment]
If you have launcher installed you can run `launcher interactive`

If you want to build from source, you can `make tables.ext`

You can also download from the CI runs. The last stable release was build in this github actions, and if you download the platform zip file, there's a `tables.ext` somewhere in it. https://github.com/kolide/launcher/actions/runs/5091390124

At some point we'll upload to the github release pages again, but I don't have an ETA on that work
