### ISSUE TITLE
Investigate the osquery watchdog (Due 2023-12)

### ISSUE THREAD

**Issue by directionless** [kolide/launcher#1224]
A long long time ago (#95, #103) we disabled the osquery watchdog. In the intervening years, both osquery and launcher have improved, and it's likely the original issue is long resolved. We should test enabling it.

_If_ we want the watchdog to also be aware of launcher, so to take launcher's resource utilization into account, we may need to patch osquery. I think if you dig into osquery, there's an option [`enable_extensions_watchdog`](https://github.com/osquery/osquery/blob/19657704043232346246efc035bf72fbd1aa723d/osquery/core/watcher.cpp#L341-L369) which is used to control whether extensions are monitored. _But_ this might only cover the extensions osquery starts. We might need to add some kind of option in here. 

We might also need an option to monitor, but not kill, launcher. This would allow the watchdog to understand the utilization and try to kill running queries. 

There's a lot of research to be done in here

slack conversation https://kolide.slack.com/archives/CGFJY1SP2/p1687964775228619

**Comment by directionless** [comment]
We need to ship this by the end of 2023

**Comment by RebeccaMahany** [comment]
Initial testing looks promising, but further refinement might be needed. `SELECT * FROM hash WHERE path LIKE '/Users/%/%%';` ran for close to an hour on my Windows machine before being denylisted.

**Comment by RebeccaMahany** [comment]
Closed by https://github.com/kolide/launcher/pull/1460 -- this will be available in the next release after v1.2.1.

**Comment by RebeccaMahany** [comment]
We are seeing one person experience the osquery watchdog shut osquery down for reasons that appear to be unrelated to distributed/scheduled queries -- reopening this issue until we understand the issue and have addressed it.
