### ISSUE TITLE
Windows desktop systray can fail to initialize

### ISSUE THREAD

**Issue by seejdev** [kolide/launcher#1241]
In certain scenarios, when launcher desktop engages the systray module, an error will occur within the [registration/initialization code](https://github.com/getlantern/systray/blob/master/systray_windows.go#L300) and fail do to an unspecified error. First, this will result in an error:

`systray error: unable to init instance: Unspecified error`

Subsequent systray API invocations will generate more errors:
`systray error: unable to set icon: tray not ready yet`
`systray error: unable to set tooltip: tray not ready yet`
`systray error: unable to addOrUpdateMenuItem: tray not ready yet`

### Reproduction Steps

This [has been observed](https://kolide.slack.com/archives/CGFJY1SP2/p1685639413823329) in at least two scenarios: first login immediately after installing a Windows Update, and first login after creating a new user. The new user case is easier to test and on Windows 11 this behavior seems to be easily reproducible.

1. Have Kolide launcher installed, desktop enabled; the launcher service should be running and you should see a launcher icon in the system tray.
2. Go to Windows control panel and create a new non-admin user
3. Switch to the new user and login
4. Observe that the launcher service is still running, and the system tray launcher icon instead is an empty area within the system tray, with no tooltip, and no menu. 

### Debugging

I did verify that this is not specific to launcher, so for the purposes of understanding this error better once you have the Windows machine in this state you can run a simple program using systray to try and more easily debug rather than having to only use the launcher application.

The first thing that needs to be better understood is exactly what error is occurring resulting in `Unspecified error`. I imagine a worthy exercise is going through the [initInstance function](https://github.com/getlantern/systray/blob/master/systray_windows.go#L300) and identifying every place that an error can be returned, and logging exactly what API is giving that error, and preferably what the corresponding Windows error code is. Once we know what API is failing and for what error reason, there should be more runway to identify if this is something that can be worked around either in systray package or not.

**Comment by RebeccaMahany** [comment]
This was fixed by https://github.com/kolide/launcher/issues/1717.
