### ISSUE TITLE
Modify package-builder so that it can be used by a generic organization. 

### ISSUE THREAD

**Issue by murphybytes** [kolide/launcher#126]
Right now package-builder expects a particular bucket name for mirroring files.  The bucket name should be set by command line. There are probably other things that are Kolide specific, these should be changed with an eye towards open sourcing the package.

**Comment by groob** [comment]
Closing this as stale, if anyone needs it please reopen. 
The mirroring code that used to live in launcher is now part of our infra tooling and package-builder is mostly standalone.
