### ISSUE TITLE
Removing the root directory or its parent results in broken desktop process on macOS and Linux

### ISSUE THREAD

**Issue by RebeccaMahany** [kolide/launcher#1264]
#### Steps to reproduce:

1. Stop or unload launcher
1. Remove the root directory (`/var/<identifier>/<hostname>`) or its parent (`/var/<identifier>`)
1. Restart launcher
1. Observe an eventual desktop user process error in the logs: `run with positional args: running subcommand desktop: timeout after 5s (6 attempts): open /var/<identifier>/<hostname>/desktop_<uid>: permission denied`

#### Explanation

The installer creates the root directory with 0755. However, if that root directory is ever removed (as in steps to reproduce above), launcher re-creates the root directory. It does this with permissions 0700 [here](https://github.com/kolide/launcher/blob/main/cmd/launcher/launcher.go#L113) -- however, in practice, the directory is created with 0744. It's not clear to me exactly why we're ending up at 0744.

Either way, the desktop process is not able to access the socket created for it at `/var/<identifier>/<hostname>/desktop_<uid>`, because even though we do chown that file, since the directory does not have r_x permissions the user process cannot list files inside it.

#### Resolution

When making the root directory on startup, we can't just update to set permissions to 0755 -- the issue is not fixed because `os.MkdirAll` respects umask settings as well. However, if we chmod both the root directory and its parent, then the permissions issue is resolved and the directory looks as it would after a regular install.

**Comment by directionless** [comment]
If I think about history, I think I've never wholly settled on whether the root directory is `700 or `755`. _Most_ of the files there aren't sensitive, and the ones that are are `600` directly -- So `755` feels right, and it makes it relative easy to use that as a place for things meant to be world readable.

But then there's still like that mkdir...

I think it would be reasonable to do that creation as `755` and not `700`.

And to add something to how the desktop process spawns to make sure the directories are accessible. But, I think it would be unacceptable for launcher to set permissions of any non-kolide directory. `/var/kolide-k2` is okay, but I don't think we can reliable say `rootdir/..`. Might have to hardcode a check of that for whether or not it's `kolide`

**Comment by RebeccaMahany** [comment]
@directionless that makes sense to me -- I updated the [PR](https://github.com/kolide/launcher/pull/1265) to only chmod the parent if the parent is `/var/kolide-k2`.
