### ISSUE TITLE
Refactor kolide_best_practices to be aware of query context

### ISSUE THREAD

**Issue by marpaia** [kolide/launcher#127]
Right now, every execution of `select foo from kolide_best_practices;` executes every best practices query. The implementation should be refactored to be aware of the supplied query context to ensure only the required columns are calculated and returned.

For example, running the following query:

```
SELECT sip_enabled FROM kolide_best_practices;
```

should be just a light proxy on top of:

```
SELECT enabled AS compliant FROM sip_config WHERE config_flag='sip'
```

**Comment by directionless** [comment]
Closing as stale
