### ISSUE TITLE
Launcher probably broken on m1 machines running Big Sur

### ISSUE THREAD

**Issue by directionless** [kolide/launcher#1276]
Customer [report](https://kolide.slack.com/archives/CFPMXV7CZ/p1689635933981329) that launcher isn't working on Big Sur:
```
dyld: Symbol not found: _kIOMainPortDefault
 Referenced from: /usr/local/kolide-k2/bin/launcher (which was built for Mac OS X 12.0)
 Expected in: /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
zsh: abort /usr/local/kolide-k2/bin/launcher doctor"
```

which I suspect might be the result of #1151

**Comment by RebeccaMahany** [comment]
Related: https://github.com/kolide/launcher/pull/1133, https://github.com/kolide/launcher/pull/1150

**Comment by directionless** [comment]
Hrm. At least a a first blush, macos-11, seems to be able to run this okay:
https://github.com/kolide/launcher/actions/runs/5742081124/job/15563848822

**Comment by directionless** [comment]
And https://github.com/kolide/launcher/actions/runs/5746094914/job/15575064966 is a `doctor` run on macos-11

**Comment by directionless** [comment]
I have not yet been able to replicate this.

https://github.com/kolide/launcher/pull/1279 brings in all the GHA runners for smoke tests, and macos-11 passed fine -- https://github.com/kolide/launcher/actions/runs/5751156346/job/15589880445

I setup a laptop with Big Sur, and running both the Big Sur beta, and 11.7.9, I can run the released launcher:
```
% ./usr/local/kolide-k2/bin/launcher --version 
{"caller":"main.go:30","msg":"Launcher starting up","revision":"6a1bfb213ab66c497645c865d19114c936af14ce","severity":"info","ts":"2023-08-03T14:26:19.275612Z","version":"1.0.12"}
launcher - version 1.0.12
  branch: 	HEAD
  revision: 	6a1bfb213ab66c497645c865d19114c936af14ce
  build date: 	2023-06-23
  build user: 	runner (runner)
  go version: 	go1.20.5
```

**Comment by directionless** [comment]
https://github.com/pulumi/pulumi/issues/11152 discusses a similar problem, and using a suggested otool command I can see:
```
$ otool -l usr/local/kolide-k2/Kolide.app/Contents/MacOS/launcher | grep -A 3 min
    minos 12.0
      sdk 13.1
   ntools 1
     tool 3
--
    minos 12.0
      sdk 13.1
   ntools 1
     tool 3
```
