### ISSUE TITLE
Fairly regular and unexplained terminations of launcher service on Windows

### ISSUE THREAD

**Issue by RebeccaMahany** [kolide/launcher#1387]
Event logs on Windows contain `The LauncherKolideK2Svc service terminated unexpectedly` fairly frequently. These are sometimes expected -- for example, when launcher autoupdates -- but I still see one or two a day that don't have a corresponding explanation in the launcher logs.

We had thought that these could be explained by throttling issues with modern standby (more details [here](https://github.com/kolide/launcher/pull/1284)), but I saw one happen while regression testing last week while my laptop was awake, so I think something else is going on.

We should try to write corresponding launcher logs when this event occurs -- maybe there's somewhere we're missing a call to `recover`?

The relevant event logs can be found by filtering Windows Logs => System with:

```
<QueryList>
  <Query Id="0" Path="System">
    <Select Path="System">*[System[Provider[@Name='Service Control Manager'] and (EventID=7031)]]</Select>
  </Query>
</QueryList>
```

**Comment by directionless** [comment]
Ha. This issue was prescient. I think it's fixed by #1699 and the other recent panic work
