### ISSUE TITLE
launcher doctor output looks malformed on Windows

### ISSUE THREAD

**Issue by RebeccaMahany** [kolide/launcher#1433]
Emojis are not properly encoded when running `& "C:\Program Files\Kolide\Launcher-kolide-k2\bin\launcher.exe" doctor | Out-String` in PowerShell on Windows. This issue is to make the output look reasonable. Dealing with encoding in PowerShell when working on the notifications was a pain -- I think it's probably not worth it to pursue emoji support just for doctor on Windows, and write out `Passing|Warning|Failing` or similar instead of the emoji on Windows.

If possible, it would be nice to be able to run `launcher.exe doctor` without having to pipe to `Out-String` to view the results, as well.

**Comment by directionless** [comment]
> If possible, it would be nice to be able to run `launcher.exe doctor` without having to pipe to `Out-String` to view the results, as well.

Yeah... IIRC this is fallout from https://github.com/kolide/launcher/pull/1007 and our choice to have a single binary

**Comment by directionless** [comment]
Well well.. [`AttachConsole`](https://learn.microsoft.com/en-us/windows/console/attachconsole?redirectedfrom=MSDN) might do it. And seems to have some go libraries. https://pkg.go.dev/github.com/minux/windows/attachconsole

**Comment by RebeccaMahany** [comment]
AttachConsole looks like it should work -- I couldn't get it working with that exact package, but doing similar plus redirecting stdout seems to do the trick
