### ISSUE TITLE
package versions should auto-increment. 

### ISSUE THREAD

**Issue by groob** [kolide/launcher#145]
Right now we build a package like `launcher-darwin-0.1.0-20-g402d86a.pkg` which takes account of the git tag, but also uses the git sha. 
Building a new package without incrementing the git tag would update the sha, but leave the numeric version the same. This is problematic, as package managers rely on incrementing numbers to decide if a copy in the repository is newer or older than the installed package. 

Affects munki, apt and yum. 

Two possible solutions to fix this:
1) use a different version scheme for packages. maybe add `time.Now().Unix()` to the package version? 
2) always increment build tags before releasing a new production package.

**Comment by erikng** [comment]
For clarity, the reason why it impacts munki is munki looks compares FILE-VERSION. Having a version with a `-` will lead to unexpected results.

**Comment by marpaia** [comment]
Can we use underscores instead of versions in the same way? Right now, the version contains the following information:

0.1.0-20-g402d86a
- Last tag is 0.1.0
- This is 20 commits since the last tag
- The commit hash of this build is g402d86a

I'd like to maintain this in the version for version of the software which are not build on a tag.

**Comment by erikng** [comment]
Best practices say you should only have dots in between. You should play with strictversion and looseversion in python. I’m pretty sure you’ll find the > and < comparisons will fail.

**Comment by groob** [comment]
I've been testing this a little bit with `looseversion` and other version schemes. I like the idea @marpaia put up of using 
```
git log `git describe --tags --abbrev=0`..HEAD --oneline|wc -l
```

But it also has a few drawbacks. For example if I make a package from a branch and my git log there is 600 small commits ahead of master the master will never catch up. 

I've been playing with this versioning scheme in another project and would like to propose it here:
```
<identifier>.<semver version>.<build-id>.pkg
```
Which ends up looking like this: 
```
com.kolide.launcher.1.2.3.01c75athaffq6z2ett9rxmmfpz.pkg
```

The above versioning scheme gives a sortable version compatible with all versioning libraries. I used an [ULID](https://github.com/ulid/spec) for the build identifier because it gives the following properties:
1. it's sortable
2. It's always unique, so if two builds of the same git tag were done, the build can be identified.

**Comment by groob** [comment]
I checked wether `-` affects python at all and I don't see an issue. 

```
>>> LooseVersion("0.3.0-43-g5aba90d-dirty") > LooseVersion("0.3.0-41-aaaaaaaa")
True
>>> LooseVersion("0.3.0-41-aaaaaaaa") > LooseVersion("0.3.0-43-g5aba90d-dirty")
False
```

**Comment by directionless** [comment]
Closing as stale.
