### ISSUE TITLE
Use lsblk instead of cryptsetup for the full-disk-encryption check

### ISSUE THREAD

**Issue by smlx** [kolide/launcher#1469]
`lsblk` is part of `util-linux` and provides much more convenient JSON output for parsing compared to `cryptsetup status`. It is also a much safer command and requires fewer privileges.

For example, here's a check for "does the / partition use full disk encryption?":

```shell
lsblk -fJ | jq '.blockdevices[].children[] | select(.children) | select(.children[].mountpoints | index("/")) | .fstype == "crypto_LUKS"'
```

The other advantage of `lsblk` is that it allows sandboxing of the Kolide `launcher` to only allow access to "/" and disallow access to other sensitive mount points. Because it requires more permissions, `cryptsetup` fails in this kind of sandbox.

**Comment by directionless** [comment]
Thank you for the suggestion! We'll try to investigate whether using `lsblk` is suitable for our purposes here.
