### ISSUE TITLE
Wrong binary path in .plist

### ISSUE THREAD

**Issue by henningwagner** [kolide/launcher#1509]
I'm using `package-manager` to bundle a `darwin-launchd-pkg` via
```
./build/package-builder make \
--hostname="our-hostname" \
--enroll_secret="our-secret" \
--osquery_version stable \
--launcher_version ./build/launcher \
--targets darwin-launchd-pkg
```
Installing this package leads to the files properly being located 
1. /usr/local/launcher/launcher (executable binary)
2. /usr/local/launcher/osquery.app

But when I inspect the `/Library/LaunchDaemons/com.launcher.launcher.plist` the assigned binary path isn't pointing to the correct entry:

```
<key>ProgramArguments</key>
      <array>
         <string>/usr/local/launcher/Kolide.app/Contents/MacOS/launcher</string>
         <string>-config</string>
         <string>/etc/launcher/launcher.flags</string>
      </array>
```

I would have expected the startup item to be
`/usr/local/launcher/launcher`
but instead it's
`/usr/local/launcher/Kolide.app/Contents/MacOS/launcher`

**Comment by henningwagner** [comment]
I've gone through the latest changes and came across the [EE licensing](https://github.com/kolide/launcher/pull/1497) tasks. That explains why things seem hard-coded for the `.../Kolide.app/...` path.

As we used the `package-builder` in the past and we wan't to avoid any licensing violation: with which version would we be good to still work with? @RebeccaMahany may I direct this question towards you 😊?

**Comment by RebeccaMahany** [comment]
Hi @henningwagner ! I think the original issue is actually not related to the EE re-licensing -- the path to the binary changing is a product of the work I did about a year ago to package launcher as an app bundle, because we wanted access to some macOS entitlements.

The workaround would be to build the app bundle (`make github-build && make github-lipo && make github-launcherapp`) and then run package-builder pointing to the built app bundle `./build/darwin.universal/Kolide.app` instead of to `./build/launcher`.

I will tag in @directionless for guidance about the EE re-licensing. 🙂

**Comment by directionless** [comment]
Hi @henningwagner 

As it stands today, `package-builder` itself is still MIT licensed, but the bulk underlying launcher code is predominantly EE licensed. This change happened between the 1.2.5 release and the 1.3.2. I think you're find to use version 1.2.5.

I'm always curious to hear about how folks are using launcher. Is there anything you can share?

**Comment by henningwagner** [comment]
Hi @RebeccaMahany and @directionless 

Happy New Year and please excuse my late reply – I was out of office during the holidays.

Thank you very much for your answers. Thanks to Rebeccas hints I was able to successfully compile and now the autostart items are working. And thanks for pointing out the licensing details, Seph.

Happy to share some details about how we are ideating to use launcher: In short the idea is to utilize it as a fleet management running based upon osquery (who would have thought 😅) to have a general overview of the clients (and to group them by tenant) and then, taking this as a foundation, to add client services like e.g. 1st level support. The idea is leaning towards a virtual help center rather than an MDM solution, although we're tinkering around remote software installation as well. The idea is pretty early stage and we're trying to figure out the moving parts.

Have a great start into 2024!
