### ISSUE TITLE
launcher kolide_grpc error

### ISSUE THREAD

**Issue by michaelkacz** [kolide/launcher#1690]
Some servers where I have the kolide launcher deployed receive an error:

Cannot call registry item: kolide_grpc

Following this error, the launcher shuts down, then stops the osqueryd task. These servers do not have internet connectivity, is there a way around this to avoid the service shutting down and disconnecting from my fleet? Along with this, is there a flag I can use to disable autoupdates? When adding "autoupdate=false" or "autoupdate false" into the launcher flags, it is an unknown command line flag.

**Comment by directionless** [comment]
Hi!

Launcher is increasingly designed to communicate with Kolide's online SaaS offering. You mentioned you're running it on servers that do not have network access, what is the purpose? What version are you running?

I cannot offhand remember if we still support disabling autoupdate, but if you omit `autoupdate` it would probably not be enabled. 

`kolide_grpc` is the name launcher registers with osquery as. This extension no longer uses grpc, but is responsible for all the server communication. To understand why it's failing, you would need to examine more debug logs.
