### ISSUE TITLE
Add disable/delete ability to the Kolide Service

### ISSUE THREAD

**Issue by directionless** [kolide/launcher#1709]
As we've worked with #1393, we've come to conclude that this functionality should be available through the device interface and not just the control interface. So at the simplest level, this issue is to add it there.

However, there is some additional worthwhile background.
1. Launcher talks to the device server through the kolide service, which is implemented in go-kit.
2. Launcher talks to the control server via some manual http stuff
3. We are going to want to start evolving the device server interfaces

I am unsure if the split we have today makes the most sense. This is partly an opportunity to think about the next things we might want networking wise.

**Comment by directionless** [comment]
@James-Pickett -- This is done, right?

**Comment by James-Pickett** [comment]
@directionless, yep this closed by https://github.com/kolide/launcher/pull/1712
