### ISSUE TITLE
Add download directory information to flare

### ISSUE THREAD

**Issue by RebeccaMahany** [kolide/launcher#1753]
It is helpful for us when troubleshooting to know which Kolide installers a user has potentially downloaded.

Requirements:

- The download checkup should run only for flares (not for `launcher doctor` or for the log checkpoint -- see [here](https://github.com/kolide/launcher/blob/main/ee/debug/checkups/checkups.go#L88))
- The download checkup should write out a list of all Kolide installers found in the downloads directory; installers will have the filename or filename suffix `kolide-launcher.msi` on Windows, `kolide-launcher.pkg` on MacOS, and `kolide-launcher.rpm`, `kolide-launcher.deb`, or `kolide-launcher.pacman` on Linux
- If possible, the checkup should include launcher version information for those files, if it's feasible and reasonable to extract that information

Checkups live [here](https://github.com/kolide/launcher/tree/main/ee/debug/checkups) in the codebase.

**Comment by 20RitikSingh** [comment]
I want to work on this.

**Comment by directionless** [comment]
Hi @20RitikSingh Is Launcher something you're generally involved with? Note that this part of our code base is covered by our [EE License](https://github.com/kolide/launcher/blob/main/ee/LICENSE) and is not open source. 

That said, you're welcome to submit a PR. We will not hold this for you, but our PRs are open.
