### ISSUE TITLE
Kolide flags sk SSH key handles as unencrypted private keys

### ISSUE THREAD

**Issue by smlx** [kolide/launcher#1768]
SSH `sk` key handles (FIDO2 token backed) stored on disk are incorrectly flagged as unencrypted private keys.

These files are unencrypted but they just contain a handle to the private key which is stored on the FIDO2 token. So kolide should not flag these as a problem.

**Comment by directionless** [comment]
@smlx I don't use FIDO2 keys. Can you provide us with some sample keys? (or are they confidential)

**Comment by smlx** [comment]
Hmm. Thinking about this some more, key handles may still be considered sensitive even though they don't contain a plaintext private key.

I'll close this issue, sorry for the noise.

**Comment by directionless** [comment]
I'm starting to dig into this.

Tinkering with a yubikey, and using it to create some resident keys, it still gives me the option to encrypt them. So I think there are four possible states: [disk|hardware] [encrypted|unencrypted]

I don't know how common it is to encrypt keys stored in hardware, but I think I would not want to misrepresent that. As is, this table appears to correctly convey that state.
