### ISSUE TITLE
Flare should include `installer-info` files

### ISSUE THREAD

**Issue by directionless** [kolide/launcher#1775]
[Ages ago](https://github.com/kolide/launcher/pull/530) I added something to launcher's installers to leave `installer-info` files on disk. We should include them in the flares. And maybe any info about likely kolide installers in the Downloads folder.

**Comment by RebeccaMahany** [comment]
> And maybe any info about likely kolide installers in the Downloads folder.

Added in https://github.com/kolide/launcher/pull/1878 🙂

**Comment by RebeccaMahany** [comment]
The installer info files live in the configuration directory => `installer-info.json`. You can call `launcher.DefaultPath(launcher.EtcDirectory)` (from [here](https://github.com/kolide/launcher/blob/main/pkg/launcher/paths.go)) to get the path to the configuration directory.

On macOS and Linux, the file lives here: `/etc/kolide-k2/installer-info.json`. We do not have this file on Windows, so we should only attempt to retrieve it on macOS and Linux.

I think this file could fit into the `installCheckup` (if we rename it from "Package Install Logs" to "Package Install").
