### ISSUE TITLE
`homebrew` table should not error when homebrew isn't installed

### ISSUE THREAD

**Issue by directionless** [kolide/launcher#1864]
I was perusing bugsnag, and I noticed we have a [lot](https://app.bugsnag.com/kolide/k2-device/errors/65368b57ff1d330008f571d2) of [errors](https://app.bugsnag.com/kolide/k2-device/errors/6661e0bb5f85da0008cd69a9) because the homebrew table can't find homebew. 
```
error generating table: failure allocating allowedcmd.Brew: homebrew not found
```

and 
```
error generating table: failure allocating allowedcmd.Brew: not found: /home/linuxbrew/.linuxbrew/bin/brew
```

This is coming from https://github.com/kolide/launcher/blob/766d939df65f7584e5fe8aedfc288d00efc610fc/ee/tables/homebrew/upgradeable.go#L45-L48

For _this_ table, I think we should identify that error, and return no results.

Digging in slightly, it seems like `validatedCommand` should have returned a different error, so I wonder if something is slightly amiss here.

In terms of solutions, it's probably more correct to plumb a custom error.

**Comment by Dharma-09** [comment]
Can I work on this issue?

**Comment by directionless** [comment]
Fixed By https://github.com/kolide/launcher/pull/1872
