### ISSUE TITLE
`kolide_system_profiler` should not support an all option

### ISSUE THREAD

**Issue by directionless** [kolide/launcher#1876]
Chatting with some coworkers, I learned that `SELECT * FROM kolide_system_profiler where datatype like "%" ` works. But it returns so much data it crashes `Terminal.app` and probably has a bunch of gnarly load. 

I think we should disable it. We should require a reasonable argument for `datatype`

https://github.com/kolide/launcher/blob/1ec19cddf4b2a6fa44a78ef1fccb5531c08a2677/ee/tables/systemprofiler/systemprofiler.go#L111

**Comment by RebeccaMahany** [comment]
You can find all valid datatypes by running `system_profiler -listDataTypes`. We should restrict the allowed values for `datatype` to one in that list.

@directionless do we also want to set a limit on the max number of datatypes that can be specified in one query?

**Comment by RebeccaMahany** [comment]
`system_profiler` documentation: https://ss64.com/mac/system_profiler.html

**Comment by RebeccaMahany** [comment]
Issue requirements:

* Disallow passing `%` as `datatype`
* Do now allow more than 3 datatypes in a query
