### ISSUE TITLE
package-builder should be able to build macOS packages on Linux

### ISSUE THREAD

**Issue by groob** [kolide/launcher#188]
To start with, we can shell out to the bomutils and use go-xar. 

Some notes from @bruienne https://gist.github.com/bruienne/ec5205408b9e52bd5cfc

**Comment by marpaia** [comment]
If we did this, we could make a page on https://kolide.com that allows people to put in hostname, enroll secret, etc. and we can output a launcher package for them! This would be cool, if people could generate packages without having to clone the repo.

**Comment by groob** [comment]
That's an idea =D

**Comment by JJediny** [comment]
Others:
- [ ] https://snapcraft.io/
- [ ] https://appimage.org/

Example:
https://keepassxc.org/download

**Comment by marpaia** [comment]
@JJediny package-builder produces DEBs and RPMs right now: https://github.com/kolide/launcher/blob/2fd6e9ec8788490711fa8aa6bea0fb263ca6dc15/tools/packaging/packaging.go#L46-L215

**Comment by groob** [comment]
Made progress here https://github.com/kolide/gcp-pkgbuild
Going to try to integrate into the launcher next.

**Comment by directionless** [comment]
Though interesting, this is not work we're pursuing at this time.
