### ISSUE TITLE
Support HTTP/1 loadbalancers like heroku

### ISSUE THREAD

**Issue by groob** [kolide/launcher#197]
Some of launcher's users host fleet on Heroku. Unfortunately heroku only supports HTTP 1.1 connections, so the client must work around this. 

There are 2 possible ways to resolve the problem:

1) use one of these Dial methods that do a connection upgrade/proxy tcp
https://github.com/lstoll/wsnet
https://godoc.org/github.com/lstoll/grpce/h2c

2) Implement a HTTP transport for the launcher. This is why we wrote the launcher with go-kit in the first place. The alternative transport might be a great investment as we deal with different loadbalancers.

**Comment by groob** [comment]
A new possibility which I really like is [Twirp](https://github.com/twitchtv/twirp)

The RPC protocol would allow re-using the .proto files so we don't have to maintain a json schema for the launcher which is a huge benefit. 

A temporary drawback is that we (or someone) would have to add support to go-kit.

**Comment by directionless** [comment]
There is now jsonrpc support
