### ISSUE TITLE
update launchd to wait until secret is present

### ISSUE THREAD

**Issue by groob** [kolide/launcher#199]
Some users would like to add the enrollment secret out of band from the install. To do that, a suggested solution is to add an `OnDemand` conditional to launchd so the process only starts after the secret is added at the right path.

**Comment by erikng** [comment]
Example of a launch agent that does this:

https://raw.githubusercontent.com/erikng/installapplications/master/payload/Library/LaunchAgents/com.erikng.installapplications.plist
