### ISSUE TITLE
Re-running failed `launcher` CI job takes an annoying amount of time

### ISSUE THREAD

**Issue by RebeccaMahany** [kolide/launcher#2001]
We have some flaky tests, and sometimes the `launcher` job (which contains these tests) fails and we have to re-run it. This takes an annoying amount of time. For example, for the Windows `launcher` job I'm looking at, `Go mod cache` takes 3m 39s, `Get dependencies` takes 1m 34s, and `Build` takes 1m 19s -- over 6.5 minutes before we get to the _actual_ part that failed, which is the tests.

Can we move the tests out of the build job (maybe to the same level as the "exec testing") so that when we re-run failed test jobs, we don't have to do as much repeated setup?

**Comment by directionless** [comment]
> Windows launcher job I'm looking at, Go mod cache takes 3m 39s, Get dependencies takes 1m 34s, and Build takes 1m 19s

IIRC the cache actions might be horrifically slow on windows. There may be better options, or simply not caching
