### ISSUE TITLE
capture osqueryd logs and format them as json

### ISSUE THREAD

**Issue by groob** [kolide/launcher#203]
Instead of writing the osqueryd logs directly to stderr, we should log them with the go-kit logger as json with a `debug` level. 

Making this change will allow us to further filter logs with `jq` and to disable them with the `SIGUSR2` signal.

**Comment by zwass** [comment]
Thank you for filing an issue for this. I have been intending to address it.

**Comment by groob** [comment]
Fixed by #204?

**Comment by zwass** [comment]
Yes, closed by #204.
