### ISSUE TITLE
unrecoverable DNS issue 

### ISSUE THREAD

**Issue by groob** [kolide/launcher#232]
I'm having a hard time tracking the root cause of this, but noticing the behavior numerous times:

it's possible for launcher to fail DNS resolution once, and then continue failing even though the DNS resolution works outside of that process. The issue happens when resolving both notary.kolide.com and the remote gRPC server. 

Tracking this bug here and will update as I get more info.

**Comment by directionless** [comment]
I suspect I've seen this several times as well.

**Comment by directionless** [comment]
This is still present.

**Comment by groob** [comment]
I suspect it's https://github.com/golang/go/issues/12524 or at least related.

**Comment by directionless** [comment]
I'm pretty sure I've seen this on windows (#563 came out of that)

**Comment by directionless** [comment]
The two cases I have both involve, I think, resolver changes. So it seems like something it failing to re-resolve correct. 

One case is in the `jsonrpc` side, which use `http.NewRequest`

The other case I have is in the autoupdate code path. Also `net/http`. The original bug also cited the grpc transports

**Comment by directionless** [comment]
A likely upstream bugs https://github.com/golang/go/issues/23427

**Comment by directionless** [comment]
I haven't seen this happen in a few years. So I'm guessing something got fixed.
