### ISSUE TITLE
package-builder deb file relies on the use of systemd which isn't used in ubuntu 14.04 so install fails

### ISSUE THREAD

**Issue by gregorypothier** [kolide/launcher#237]
error log:
...
Unpacking launcher (0.3.0-27-g15a8767) over (0.3.0-27-g15a8767) ...
Setting up launcher (0.3.0-27-g15a8767) ...
/var/lib/dpkg/info/launcher.postinst: 3: /var/lib/dpkg/info/launcher.postinst: systemctl: not found
dpkg: error processing package launcher (--install):
 subprocess installed post-installation script returned error exit status 127
Errors were encountered while processing:
 launcher

**Comment by zwass** [comment]
I believe this issue can now be solved by building your own package. See https://github.com/kolide/launcher/pull/247.

Maybe there's a way to build a package that supports both?

**Comment by directionless** [comment]
Current package-builder has support for building various flavors.
