### ISSUE TITLE
Use launcher to run queries through a running extension socket

### ISSUE THREAD

**Issue by marpaia** [kolide/launcher#239]
## Overview

This issue outlines a proposal to add a set of features that allow for the periodic execution of osquery queries with all launcher-provided extensions/tables available. The general way to use this feature would be a two step process.

### Step 1: Create a launcher-enabled extension manager socket

First, one would create a launcher instance that will establish an extension socket at a known location:

```
launcher socket --path=/var/launcher/launcher.em
```

#### Option 1: Running queries via stdin

Let's say we had a JSON file on disk with a name and query for each query that one would want to run:

```
{
  "queries": {
    "apps": "select name, path from apps limit 2",
    "hostname": "select hostname from system_info"
  }
}
```

Run the queries via stdin:

```
cat /path/to/queries.json | launcher query --socket=/var/launcher/launcher.em
```

#### Option 2: Running queries defined in a file

First, one must create a JSON file on disk with a name and query for each query that one would want to run:

```json
{
  "queries": {
    "apps": "select name, path from apps limit 2",
    "hostname": "select hostname from system_info"
  }
}
```

Run the queries using that extension socket:

```
launcher query --queries=/path/to/queries.json --socket=/var/launcher/launcher.em
```

This will produce output like:

```json
{
  "results": {
    "apps": [
      {"name":"1Password 6.app","path":"\/Applications\/1Password 6.app"},
      {"name":"Adobe Acrobat Reader DC.app","path":"\/Applications\/Adobe Acrobat Reader DC.app"},
      {"name":"App Store.app","path":"\/Applications\/App Store.app"},
      {"name":"AppZapper.app","path":"\/Applications\/AppZapper.app"},
      {"name":"Audacity.app","path":"\/Applications\/Audacity.app"}
    ],
    "hostname": [
      {"hostname":"marpaia"}
    ]
  }
}
```

### Introducing commands into `launcher`

Right now, when we run the `launcher` binary, there are only flags. For example, to connect a launcher instance to a server, you'd say something like:

````
launcher --hostname=foo.bar.com:443 --enroll_secret_path=/foo/bar/secret
```

The new model introduces `launcher query` and `launcher socket` commands to launcher. I don't think it will be too difficult to introduce this support to the main.go file.

**Comment by marpaia** [comment]
@BlakeWilliams the results are included in a top-level key of their own because if the queries you submit are incorrect or what have you, we might emit a response where the top-level key was `error` or something different.

**Comment by BlakeWilliams** [comment]
Makes sense to me. I could also see relying on exit status making sense.

**Comment by marpaia** [comment]
As implemented in #240, here's an extremely minimal example of how you could query a socket via JavaScript.

First, start an instance with a socket at `/tmp/osquery.sock`:

```
launcher socket --path=/tmp/osquery.sock
```

Consider `exec.js`:

```js
const exec = require('child_process').exec

const command = exec("launcher query --socket=/tmp/osquery.sock", function(error, output) {
  if (error) {
    console.log("error", error)
  } else {
    console.log(output)
  }
})

command.stdin.write('{"queries":{"practices": "select * from kolide_best_practices"}}')
command.stdin.end()
```

Running `exec.js`:

```
$ node exec.js
{
    "results": {
        "practices": [
            {
                "bluetooth_sharing_disabled": "1",
                "disc_sharing_disabled": "1",
                "file_sharing_disabled": "1",
                "filevault_enabled": "1",
                "firewall_enabled": "1",
                "gatekeeper_enabled": "1",
                "internet_sharing_disabled": "1",
                "printer_sharing_disabled": "1",
                "remote_apple_events_disabled": "1",
                "remote_login_disabled": "1",
                "remote_management_disabled": "1",
                "screen_sharing_disabled": "1",
                "sip_enabled": "1"
            }
        ]
    }
}

```

**Comment by BlakeWilliams** [comment]
@marpaia For our use case, will the socket always be in a known location? I assume the app won't have to run `launcher socket --path=/tmp/osquery.sock` as well?

**Comment by marpaia** [comment]
@BlakeWilliams for our use-case, the `launcher socket` will be ran separately at a known path that will be passed in to your app as an environment variable or something. We will have to reason a bit about creating a representative development environment for this.

**Comment by BlakeWilliams** [comment]
Awesome, I think we're on the same page then.

> that will be passed in to your app as an environment variable or something.

I think that sounds good, but we'll have to think around the cases of when a user closes the app and how to handle this if they start the app manually after quitting (if they can).
