### ISSUE TITLE
Document uninstall process

### ISSUE THREAD

**Issue by rocketnova** [kolide/launcher#243]
I've built the packages using `package-builder` and installed the macOS package on a host machine.

What's the proper way to uninstall it? Is there an uninstaller? or a way to build an uninstaller? Thanks!

**Comment by groob** [comment]
You can use the document here to get a list of files installed by the pkg and remove them yourself. 

https://wincent.com/wiki/Uninstalling_packages_(.pkg_files)_on_Mac_OS_X

That should take care of uninstallation. I'll keep this open until we can provide a script.

**Comment by rocketnova** [comment]
@groob Thanks for the quick response. It'll be good to have a script that can be deployed for uninstalling.

**Comment by rocketnova** [comment]
Great. Thanks @marpaia

**Comment by rocketnova** [comment]
@marpaia I'm not sure kolide launcher installs osqueryi (maybe it used to and it doesn't anymore?), but running the script as is, it throws an error `osqueryi: command not found`. If your team is just using this script in a dev environment, then it doesn't matter, but thought I should point it out in case you are recommending this as the proper way to uninstall kolide launcher from production hosts.

**Comment by marpaia** [comment]
Definitely don't run that script as is with a normally packaged launcher. It's not meant as an official or product anything. I'm just sharing it for context.

**Comment by rocketnova** [comment]
Ok thanks!

**Comment by rocketnova** [comment]
Please re-open. Talked with @groob at querycon about this. Not high priority, but it would be great to get an official/production uninstaller. Thanks!

**Comment by 0xmachos** [comment]
I'm aware that @rocketnova asked about macOS. I'm posting for others looking for uninstall instructions for Linux. 

I installed Launcher for Debian Linux (`kolide-osquery-launcher.deb`) via `dpkg -i kolide-osquery-launcher.deb`.

I was able to uninstall launcher by executing `sudo dpkg --remove launcher` then rebooting the system. 

This will leave some config files around, you can execute `sudo dpkg --purge launcher` to delete them. `dpkg` won't delete directories which aren't empty, for example I was given the following warning: 
```
dpkg: warning: while removing launcher, directory '/usr/local/kolide/bin' not empty so not removed
dpkg: warning: while removing launcher, directory '/var/kolide/dichiye.launcher.kolide.com-443' not empty so not removed
```

You can `rm` these manually and as far as I can tell that's a successful uninstall.  

I'd like to see this issue reopened, an official uninstaller for all supported platforms should be provided by Kolide.

**Comment by marpaia** [comment]
I agree that we should have better official documentation on how to purge a launcher installation.

**Comment by 0xmachos** [comment]
@marpaia What form do you envisage the uninstaller taking? 

I don't know `Go` but I'd be happy to write a bash script which automates the steps I mentioned in my original comment. 

Also thank you for reopening the issue.

**Comment by marpaia** [comment]
@0xmachos I was thinking of adding a comprehensive guide to the [Launcher Docs](https://github.com/kolide/launcher/tree/master/docs) with copy-pastable commands.

We could create a tool to uninstall launcher, but I would prefer if it were written in Go and, ideally, easily `go get`-able from any platform that the launcher works on.

**Comment by 0xmachos** [comment]
I can make a start on the guide for Debian. 

Would you want that added to [`launcher.md`](https://github.com/kolide/launcher/blob/master/docs/launcher.md)?

**Comment by marpaia** [comment]
Yeah, we can either add a section in `docs/launcher.md` or create a new file at `docs/uninstalling.md` and link to it in [`docs/README.md`](https://github.com/kolide/launcher/blob/master/docs/README.md). I think either solution would be OK.

**Comment by 0xmachos** [comment]
@marpaia Could you have a look at https://github.com/0xmachos/launcher/commit/d9f5cd47c5713117813725cf236e868ff2062cd4 and let me know if that's the kind of format you're after? Do the instructions need to be more verbose?

**Comment by marpaia** [comment]
Yeah, that looks good to me, other than the caveat that the directories at the end that have to be deleted manually will be different based on how the package was built (ie: it could be `/var/foo/foobar-com-443` or something). Might be worth explaining that for those that like to reads docs verbatim?

**Comment by marpaia** [comment]
Nice, thanks so much @0xmachos! I made some light edits and merged that in. Thanks for getting this doc started as we can now iteratively work on expanding it by adding more platforms and install methods over time.

**Comment by 0xmachos** [comment]
@marpaia I've attempted to add macOS uninstall instructions for the launcher in #333

**Comment by polak785** [comment]
This issue can be closed, right? cf. https://github.com/kolide/launcher/blob/master/docs/uninstalling.md

Or we wait for an uninstaller :D

**Comment by directionless** [comment]
Those docs seem good enough. Paths vary based on what `identifier` it was packaged with, but this issue is super stale
