### ISSUE TITLE
Add UserApproved status for MDM info table

### ISSUE THREAD

**Issue by groob** [kolide/launcher#251]
Apple now allows querying the user approved status of an mdm profile. Adding this information to the mdm table would be very valuable to users. I’ll test it and implement it ASAP. 

Something important to consider here is that adding new columns to tables can be a breaking changes for users that rely on select * from queries. I want to propose adding a new table called `kolide_mdm_info_v2`, but we haven’t done that kind of versioning in the osquery world yet, so I want to open it up for discussion. Thoughts?

**Comment by clburlison** [comment]
While adding UAMDM you might as well add DEP status. It’s just one more line of stdout that you would be parsing.

**Comment by groob** [comment]
Agreed. Thanks for the suggestion.

**Comment by NickTitle** [comment]
I would love to see schema version in the naming, with two special cases
`foo` is always the first table version
`foo_v2` is always the second
`foo_latest` is considered edge

This gives you ease of use, stability, and the option for latest features

**Comment by erikng** [comment]
Agreed with what @clburlison and @NickTitle said.
