### ISSUE TITLE
Add capabilities for certificate pinning

### ISSUE THREAD

**Issue by zwass** [kolide/launcher#253]
Allow the user to provide a comma separated list of hex encoded SHA256 hashes of `SubjectPublicKeyInfo` of the certs they would like to pin against. When making a TLS connection, Launcher will verify that one of the certs in the chain matches the provided pin hashes. This provides flexibility for the user to pin against leaf, intermediary, or root certificates.

Example usage:
 ```
launcher --public_key_pins=60b87575447dcba2a36b7d11ac09fb24a9db406fee12d2cc90180517616e8a18
```

If this flag is provided, it will be checked _in addition to_ the normal TLS handshake. If no value is provided, no certificate pinning checks will be performed, and only the usual TLS handshake will take place.

**Comment by marpaia** [comment]
Perhaps we can call the flag `tls_pins` for brevity? We already need extra documentation to define that the values must be a comma separated list of hex encoded SHA256 hashes of SubjectPublicKeyInfo of the certs they would like to pin against, so I don't think `tls_pins` is any more lossy than `public_key_pins`.
