### ISSUE TITLE
support for configuring flags && extensions.load

### ISSUE THREAD

**Issue by monkykap** [kolide/launcher#259]
Additional flags are needed for features such as process/socket auditing or osquery extensions. 

Right now using additional flags requires custom build of launcher ([runtime.go](https://github.com/kolide/launcher/blob/master/osquery/runtime.go#L139)). Adding to extensions.load could be another flag, although this can be handled after the fact by editing the package or using an orchestration tool.

**Note: This is related to issue [96](https://github.com/kolide/launcher/issues/96).**

ref: https://osquery.readthedocs.io/en/stable/deployment/process-auditing/

**Comment by directionless** [comment]
Additional flags are supported via https://github.com/kolide/launcher/pull/613

I believe the best way to pass extensions is to use `--extensions_autoload`. Auditing is generally best done through the configuration file
