### ISSUE TITLE
support a standard osquery extension

### ISSUE THREAD

**Issue by groob** [kolide/launcher#260]
Right now the launcher creates a dummy `.ext` file which osquery loads as an extension but it registers all the plugins from the launcher's binary, which also acts as a process manager and autoupdater. In several discussions with users offline and in osquery slack the desire to use the launcher just for it's tables came up. I am opening this issue to start a discussion around several related concerns:

1. Give users a mode where they run osqueryd with just a binary extension for the tables. This is presently covered by `cmd/development-extension`, but can be cleaned-up/generalized better. 

2. Discuss what should happen with extensions which are not table plugins, like loggers and config plugins.
My own 2c here is that [writing your own .ext](https://github.com/kolide/go-extension-tutorial) with osquery-go is so simple that worrying about providing configuration to these plugins is not really worth it.

3. Discuss launcher's ability to manage an `extensions.load` file for other third party extensions which it could autoload. There's a number of interesting extensions out there, like [profiles](https://github.com/andrew-d/osquery-profiles) and [efigy](https://github.com/trailofbits/osquery-extensions). Securely hosting and autoupdating these is a concern for many users and the launcher is already equipped with a lot of the building blocks to make this experience better.

**Comment by groob** [comment]
Some progress on this, but leaving the issue open:

If anyone wants just the tables:
`go build -o build/tables.ext ./cmd/launcher.ext`
and if anyone wants just the gRPC transport:
`go build -o build/grpc.ext ./cmd/grpc.ext`

Either/both extensions can be loaded via extensions.load.

**Comment by directionless** [comment]
I'm going to close this. I think it represents a floating oddity in how extensions are managed. Progress here requires some larger change in the extension ecosystem.
