### ISSUE TITLE
Audit logging

### ISSUE THREAD

**Issue by mcburrlin** [kolide/launcher#271]
As part of a few informal questions on the Kolide slack channel, I'd like to ask a few open ended questions about auditing within Kolide.

Are there any existing plans or backlog features related to adding in audit logs?

Are there any existing plans to enhance the existing auditing?
i.e. 
deleted_by: kolide_admin <-- Can we enrich with things like IP address, user agent, generic HTTP headers?
method: DeleteInvite <-- Any other details about what user's invite was deleted? UserId or something else?

Currently, ad-hoc queries are stored in the MySQL database (not sure how long they stay here). So, I can just run a script to pull all queries and join it against the user table and write it to disk. This way I can see what users are running what queries (which are not saved). Would you consider embedding something like this as a core feature? Being able to turn on/up things like this could be very useful, if not for peace of mind for actual compliance. 

I'm aware of the development work being done on fleet-ctl -- but not intimately, so maybe some of these issues are being tackled there. 

Just trying to get the conversation going about auditing, thanks :)

Edit: Realized I opened this in kolide/launcher, probably needs to be in kolide/fleet.

**Comment by groob** [comment]
Hi @mcburrlin 

This issue needs to be in `kolide/fleet`. Please re-open it there.
