### ISSUE TITLE
TUF metadata nonexistent, hundreds of running processes on OS X

### ISSUE THREAD

**Issue by zbuc** [kolide/launcher#293]
We're having an issue with some machines in our fleet where hundreds of instances of the OSQuery extension are being started.

The commonality of these, going by the error logs, seems to be that the TUF metadata is missing.

```{"caller":"launcher.go:386","component":"launcher","launching osqueryd updater service: creating tuf client: getting local targets role: local target read from file: open /var/osquery/host-port/osqueryd-tuf/targets.json: no such file or directory":"(MISSING)","level":"info","ts":"2018-06-06T19:52:31.891060614Z"}```

```root             88268   0.0  0.0 558433168   1492   ??  S     2:45PM   0:00.00 /usr/local/osquery/bin/osquery-extension.ext --socket /var/osquery/host-port/osquery.sock --timeout 3 --interval 3
root             88220   0.0  0.0 558433168   1032   ??  S     2:44PM   0:00.01 /usr/local/osquery/bin/osquery-extension.ext --socket /var/osquery/host-port/osquery.sock --timeout 3 --interval 3
root             87962   0.0  0.0 558433168   1032   ??  S     2:43PM   0:00.00 /usr/local/osquery/bin/osquery-extension.ext --socket /var/osquery/host-port/osquery.sock --timeout 3 --interval 3```

**Comment by groob** [comment]
// cc @zwass on the "hundreds of instances of the OSQuery extension are being started"
I think that is related to https://github.com/kolide/osquery-go/issues/56

I'll look into why the tuf metadata was not bootstrapped correctly.

**Comment by prjackson72** [comment]
Another thing we noticed is that before the 
`osqueryd-tuf/targets.json: no such file or directory` messages begin along with the multiple instances of the extension, there's a log that says: 

`{"caller":"launcher.go:386","component":"launcher","creating local TUF repo: Asset autoupdate/assets/osqueryd-tuf not found":"(MISSING)","level":"info","ts":"2018-06-05T16:40:54.365614148Z"}`

**Comment by zwass** [comment]
We have identified an orthogonal issue that is causing the extension process not to die when osquery/launcher die. We now need to get to the bottom of the root issue which is this TUF issue (which is causing osquery/launcher to die).

Is the binary on this machine exactly the same as the binaries on other, working machines (does the SHA match)?

**Comment by prjackson72** [comment]
@zwass Yes it's the same one

**Comment by rhuddleston** [comment]
I'm running into this exact issue on a bunch of laptops when they tried installing. Let me know if there is anything I can do to help diagnose this issue.

**Comment by rhuddleston** [comment]
{"caller":"launcher.go:386","component":"launcher","creating local TUF repo: could not recurse into createTUFRepoDirectory: Asset autoupdate/assets/osqueryd-tuf/.root.json.swp not found":"(MISSING)","level":"info","ts":"2018-07-13T22:08:12.171874286Z"}

/var/launcher/fleet-api.goquiq.com/osqueryd-tuf/.root.json.swp dir exits

**Comment by directionless** [comment]
This seems pretty old, and much has been rewritten or updated. Feel free to reopen if there are still questions
