### ISSUE TITLE
undefined variable

### ISSUE THREAD

**Issue by salTermine** [kolide/launcher#307]
Hi, 
I am installing kolide launcher on Ubuntu server 16.04.  I already have kolide fleet up and running no problem.  I also installed osquery and that worked fine. When i run the following from inside the launcher folder:
make deps --> works
make xp --> osquery/table/airdrop_darwin.go45:16: undefined: copyPreferenceValue
                    osquery/table/patform_tables_darwin.go:18:3: undefined: MacOSUpdate
I get these two errors when I run make xp. am i missing anything config wise? 
if you need more information let me know.

**Comment by groob** [comment]
What version of Go are you using?

**Comment by groob** [comment]
Nevermind, it's not the go version, it's that you're trying to compile the darwin binary from linux, but CGO is not available there. I'll make a note to guard those files against CGO. 

Try running `make build` instead of `make xp`, it will compile only for your current platform.

**Comment by salTermine** [comment]
I ran make build that seemed to work but then when I run:
make deps
make package-builder 
I get the same undefined errors as before

**Comment by groob** [comment]
`package-builder` calls the `xp-launcher` target which gets you back to the issue I mentioned above. 

We'll try to get a fix for this soon. Until then you can try to either re-arrange the Makefile targets to compile linux only versions of everything, or you can check out the stable release tag.

**Comment by salTermine** [comment]
ok, and thank you for responding quick!

**Comment by salTermine** [comment]
Another quick question:
You mentioned that I am trying to compile the darwin binary from linux. which is true. I would like to be able to compile for all 3 OS

**Comment by salTermine** [comment]
Which older stable release then can I use then. pre mac specific tables that you added?

**Comment by groob** [comment]
Probably 0.5.3 and below are good to build, but 0.5.0 is the latest stable release:
https://github.com/kolide/launcher/releases

**Comment by salTermine** [comment]
ok so I installed launcher 0.5.0 everything compiled and installed.
when I ran:
~/src/github.com/kolide/launcher$ ./build/package-builder make -hostname=10.0.40.112:8080 -enroll_secret="VEV0HLPEJ04CS4wiqa9VqSYG77lqUgdM" --insecure
could not generate packages: could not generate macOS package: could not create macOS package: exec: "pkgbuild": executable file not found in $PATH

I get this error.

**Comment by SeppBender** [comment]
Try this: 

```
diff --git a/Makefile b/Makefile
index 8091239..f105eb3 100644
--- a/Makefile
+++ b/Makefile
@@ -75,7 +75,7 @@ xp: xp-launcher xp-extension
 xp-codesign: xp codesign-darwin

 xp-launcher: .pre-build .pre-launcher
-       GOOS=darwin go build -i -o build/darwin/launcher -ldflags ${KIT_VERSION} ./cmd/launcher/
+       @if [ $(CURRENT_PLATFORM) = "darwin" ] ; then GOOS=darwin go build -i -o build/darwin/launcher -ldflags ${KIT_VERSION} ./cmd/launcher/ ; fi
        GOOS=linux CGO_ENABLED=0 go build -i -o build/linux/launcher -ldflags ${KIT_VERSION} ./cmd/launcher/
        ln -f build/$(CURRENT_PLATFORM)/launcher build/launcher
```
This disables the launcher build on linux which currently won't work

**Comment by directionless** [comment]
Both the make process and package-builder have been re-written. I don't think this is applicable any more
