### ISSUE TITLE
make launcher error

### ISSUE THREAD

**Issue by gdotp** [kolide/launcher#310]
receive the following error when trying to make launcher:

# github.com/kolide/launcher/osquery/table
osquery/table/corefoundation_helpers_darwin.go:29: invalid operation: C.CFTypeRef(val) != 0 (mismatched types C.CFTypeRef and int)
osquery/table/corefoundation_helpers_darwin.go:77: invalid operation: C.CFTypeRef(ref) == 0 (mismatched types C.CFTypeRef and int)
make: *** [launcher] Error 2

**Comment by zwass** [comment]
Please upgrade to Go 1.10. I'll add a note about this in the docs.
