### ISSUE TITLE
deb launcher begins version string with nondigit causing ubuntu error

### ISSUE THREAD

**Issue by gregorypothier** [kolide/launcher#312]
dpkg: error processing archive launcher-linux-c5e8d0a.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 2 package 'launcher':
 error in 'Version' field string 'c5e8d0a': version number does not start with digit
Errors were encountered while processing:
 launcher-linux-c5e8d0a.deb

*I manually changed the version in the control file and repackaged and ran, but I think this workaround might not be effective as it sometimes fails postinstall script.

**Comment by directionless** [comment]
I'm not really sure what caused this, but all the packaging has long been overhauled and versions come from the git version these days
