### ISSUE TITLE
Package builder for ubuntu

### ISSUE THREAD

**Issue by gnomefish** [kolide/launcher#334]
Hi there,

I have installed package-builder on MACOS, I was wondering is there a similar tool (one that create an ubuntu .deb installer file) that I can install on ubuntu? I understood package-builder is only on MACOS?

Many thanks,
Luk

**Comment by groob** [comment]
`package-builder` builds deb and rpm packages. it's currently tied to builds on macos due to also building mac packages, but there's a way to turn that off by editing the code. 

All it does though is use `fpm` to build a package. You can look at `pkg/packaging` for the details.

**Comment by gnomefish** [comment]
Hi Groob thanks for the reply, I'm not that familiar with the internals I'm afraid. just trying to find a way to build a deb package from my ubuntu fleet servers without needing a MAC.

Cheers,
Luk
