### ISSUE TITLE
Building on FreeBSD results in undefined: findChromeStateFiles

### ISSUE THREAD

**Issue by sullrich** [kolide/launcher#335]
Trying to build on FreeBSD and running into this error:

mkdir -p build/darwin
mkdir -p build/linux
go build -i -o build/launcher -ldflags " -X github.com/kolide/launcher/vendor/github.com/kolide/kit/version.appName=launcher -X github.com/kolide/launcher/vendor/github.com/kolide/kit/version.version=0.5.5-17-g8dbab4c -X github.com/kolide/launcher/vendor/github.com/kolide/kit/version.branch=master -X github.com/kolide/launcher/vendor/github.com/kolide/kit/version.revision=8dbab4cc0e73256587719d9f1f57390a1810f5b6 -X github.com/kolide/launcher/vendor/github.com/kolide/kit/version.buildDate=2018-07-30T18:38:01Z -X github.com/kolide/launcher/vendor/github.com/kolide/kit/version.buildUser=root -X github.com/kolide/launcher/vendor/github.com/kolide/kit/version.goVersion=go1.10.3" ./cmd/launcher/
# github.com/kolide/launcher/pkg/osquery/table
pkg/osquery/table/email_addresses.go:26:33: undefined: findChromeStateFiles

Noticed a commit earlier this month that added multi platform compatibility.     Is this easily fixable?

**Comment by directionless** [comment]
This code has been heavily refactored since this was opened. If there is still an issue, feel free to re-open or comment.
