### ISSUE TITLE
make package builder codesign error

### ISSUE THREAD

**Issue by furby** [kolide/launcher#392]
> What version of launcher are you using (launcher --version)?

Launcher - version 0.6.0-13-gaebec12
  branch: 	master
  revision: 	aebec129d875aae8d814d0561993301673e73062
  build date: 	2018-12-19
  build user: 	furby (furby)
  go version: 	go1.11.4

>What operating system are you using?

MacOS 10.14.1

>What did you do?
Ran the 
`$ make package-builder` command

>What did you expect to happen?

Package builder tool to compile

>What happened instead?

```
furby:launcher furby$ make package-builder
go run cmd/make/make.go -targets=launcher -linkstamp -os=darwin
go run cmd/make/make.go -targets=launcher -linkstamp -os=linux
go run cmd/make/make.go -targets=launcher -linkstamp -os=windows
go run cmd/make/make.go -targets=extension -os=darwin
go run cmd/make/make.go -targets=extension -os=linux
go run cmd/make/make.go -targets=extension -os=windows
codesign --force -s "" -v ./build/darwin/launcher
error: The specified item could not be found in the keychain.
make: *** [codesign-darwin] Error 1
```

**Comment by groob** [comment]
you need to specify the env var pointing to the codesign identity. This is not an error, perhaps lack of documentation.

**Comment by groob** [comment]
https://github.com/kolide/launcher/blob/aebec129d875aae8d814d0561993301673e73062/Makefile#L50

make sure you have `CODESIGN_IDENTITY` defined and pointed to a keychain identity with a code sign certificate.

**Comment by furby** [comment]
Just edit that line in the Makefile?
What form does the `"${CODESIGN_IDENTITY}"` need to take?
Just the common name?
`${Developer ID Installer: furby (224845TH)`

**Comment by groob** [comment]
dont edit the makefile. export the env var. 
```
export CODESIGN_IDENTITY=Developer ID Application: furby (224845TH)```

note the `Developer ID Application` instead of `Installer`. you can't use the installer certificate for code signing purposes.

**Comment by furby** [comment]
I thought this would work. 
`$make package-builder -e CODESIGN_IDENTITY="Developer ID Application: furby (224845TH)"`
Doesn't say it cant' find it in the Keychain now but gives the 
```
codesign --force -s "" -v ./build/darwin/launcher
: no identity found
make: *** [codesign-darwin] Error 1
```

**Comment by groob** [comment]
did you try `export` ? does that produce the same error?

**Comment by furby** [comment]
`make package-builder export CODESIGN_IDENTITY="Developer ID Application: furby (224845TH)"`?

Yes, gives the same error

**Comment by groob** [comment]
```
export CODESIGN_IDENTITY="Developer ID Application: furby (224845TH)"
```

THEN

```
make package-builder
```

**Comment by furby** [comment]
Same error as above there
`: no identity found`

**Comment by groob** [comment]
Well, what happens when you run 
```
codesign --force -s 'Developer ID Application: furby (224845TH)' -v ./build/darwin/launcher
```

Either you have the identity in your keychain or you don't. Or you do but have a typo/are not exporting the env var correctly.

**Comment by furby** [comment]
You're right, I had a typo when I did the export there. Seems to work when I fixed it but I'm still getting this no identity.

```
$ make package-builder
go run cmd/make/make.go -targets=launcher -linkstamp -os=darwin
go run cmd/make/make.go -targets=launcher -linkstamp -os=linux
go run cmd/make/make.go -targets=launcher -linkstamp -os=windows
go run cmd/make/make.go -targets=extension -os=darwin
go run cmd/make/make.go -targets=extension -os=linux
go run cmd/make/make.go -targets=extension -os=windows
codesign --force -s "Developer ID Application: furby (224845TH)" -v ./build/darwin/launcher
./build/darwin/launcher: replacing existing signature
./build/darwin/launcher: signed Mach-O thin (x86_64) [launcher]
codesign --force -s "" -v ./build/darwin/osquery-extension.ext
: no identity found
make: *** [codesign-darwin] Error 1
```

I also checked it had code signing  and it does

```
$ security find-identity -p codesigning

Policy: Code Signing
  Matching identities
  1) EF9F..... "Developer ID Application: furby (224845TH)"
     1 identities found
```

It's not  giving the keychain error so I'm wondering what's missing

**Comment by groob** [comment]
it looks like you targeted the correct identity for `launcher` but then ended up with an empty string for the extension again. I'm not sure why that is.

**Comment by furby** [comment]
That got it!
I'm not sure what I did differently the second time but it worked

`$ export CODESIGN_IDENTITY='Developer ID Application: furby (224845TH)'`

```
$ make package-builder
go run cmd/make/make.go -targets=launcher -linkstamp -os=darwin
go run cmd/make/make.go -targets=launcher -linkstamp -os=linux
go run cmd/make/make.go -targets=launcher -linkstamp -os=windows
go run cmd/make/make.go -targets=extension -os=darwin
go run cmd/make/make.go -targets=extension -os=linux
go run cmd/make/make.go -targets=extension -os=windows
codesign --force -s "Developer ID Application: furby (224845TH)" -v ./build/darwin/launcher
./build/darwin/launcher: signed Mach-O thin (x86_64) [launcher]
codesign --force -s "Developer ID Application: furby (224845TH)" -v ./build/darwin/osquery-extension.ext
./build/darwin/osquery-extension.ext: signed Mach-O thin (x86_64) [osquery-extension]
go run cmd/make/make.go -targets=generate-tuf
go run cmd/make/make.go -targets=package-builder -linkstamp```

Thanks for all the help. I'll write the steps down for anyone who might encounter the same problem

**Comment by directionless** [comment]
Glad it helped!
