### ISSUE TITLE
Package built launcher error

### ISSUE THREAD

**Issue by calvinkim93** [kolide/launcher#393]
Built launcher with `package-builder make --hostname=host --enroll_secret=secret --insecure --insecure_grpc --autoupdate --update_channel=nightly` 

Deployed the .pkg on a macbook and /var/log/launcher/stderr.log contains the error: 

`{"caller":"updater.go:59","msg":"updater started","severity":"info","ts":"2018-12-20T18:04:17.296181Z"}
{"caller":"updater.go:59","msg":"updater started","severity":"info","ts":"2018-12-20T18:04:17.296233Z"}
{"caller":"extension.go:130","err":"enrolling host: query enrollment details: query enrollment details: could not query the extension manager client: EOF","msg":"extension interrupted","severity":"info","ts":"2018-12-20T18:04:20.952562Z"}
{"caller":"extension.go:135","err":"while shutting down instance: running extension server: registering extension: read unix -\u003e/var/launcher/{serverip}-8080/osquery.sock: i/o timeout","msg":"error shutting down runtime","severity":"info","ts":"2018-12-20T18:04:20.953021Z"}
{"caller":"runtime.go:377","err":"running extension server: registering extension: read unix -\u003e/var/launcher/{serverip}-8080/osquery.sock: i/o timeout","msg":"unexpected restart of instance","severity":"info","ts":"2018-12-20T18:04:20.953052Z"}
{"caller":"updater.go:74","err":"enrolling host: query enrollment details: query enrollment details: could not query the extension manager client: EOF","msg":"updater interrupted","severity":"info","ts":"2018-12-20T18:04:20.953114Z"}
{"caller":"updater.go:74","err":"enrolling host: query enrollment details: query enrollment details: could not query the extension manager client: EOF","msg":"updater interrupted","severity":"info","ts":"2018-12-20T18:04:20.953225Z"}
{"caller":"launcher.go:323","err":"enrolling host: query enrollment details: query enrollment details: could not query the extension manager client: EOF","msg":"interrupted","severity":"info","ts":"2018-12-20T18:04:20.953283Z"}
{"caller":"launcher.go:319","msg":"beginnning shutdown","severity":"info","ts":"2018-12-20T18:04:20.953343Z"}
{"caller":"logutil.go:13","run service: enrolling host: query enrollment details: query enrollment details: could not query the extension manager client: EOF":"run launcher","severity":"info","ts":"2018-12-20T18:04:20.953509Z"}`

Running with the launcher: 
./launcher --hostname={server}:8080 --enroll_secret={secret} --osqueryd_path=/usr/local/launcher/bin/osqueryd --insecure

`{"caller":"launcher.go:206","msg":"using default system root directory","path":"/var/folders/lh/5r_glzpj68q06qj5w26r55yc0000gn/T/launcher-root","severity":"info","ts":"2018-12-22T00:32:12.207694Z"}
{"caller":"client.go:114","cert_pinning":false,"grpc_secure":true,"msg":"dialing grpc server","server":"{server}:8080","severity":"info","tls_secure":false,"ts":"2018-12-22T00:32:12.209815Z"}
{"build":"ec00ef6c6c0fbc13b1dd26b533110eafa4c850b2","caller":"launcher.go:278","msg":"started kolide launcher","severity":"info","ts":"2018-12-22T00:32:12.211647Z","version":"0.6.0-15-gec00ef6"}
{"caller":"query_target_updater.go:21","msg":"query target updater started","severity":"info","ts":"2018-12-22T00:32:12.211716Z"}
{"caller":"extension.go:113","err":"enrolling host: query enrollment details: query enrollment details: could not query the extension manager client: EOF","msg":"extension interrupted","severity":"info","ts":"2018-12-22T00:32:15.641725Z"}
{"caller":"extension.go:118","err":"while shutting down instance: running extension server: registering extension: read unix -\u003e/var/folders/lh/5r_glzpj68q06qj5w26r55yc0000gn/T/launcher-root/osquery.sock: i/o timeout","msg":"error shutting down runtime","severity":"info","ts":"2018-12-22T00:32:15.642073Z"}
{"caller":"query_target_updater.go:26","msg":"query target updater interrupted","severity":"info","ts":"2018-12-22T00:32:15.642114Z"}
{"caller":"launcher.go:343","err":"enrolling host: query enrollment details: query enrollment details: could not query the extension manager client: EOF","msg":"interrupted","severity":"info","ts":"2018-12-22T00:32:15.642134Z"}
{"caller":"runtime.go:379","err":"running extension server: registering extension: read unix -\u003e/var/folders/lh/5r_glzpj68q06qj5w26r55yc0000gn/T/launcher-root/osquery.sock: i/o timeout","msg":"unexpected restart of instance","severity":"info","ts":"2018-12-22T00:32:15.642107Z"}
{"caller":"launcher.go:339","msg":"beginnning shutdown","severity":"info","ts":"2018-12-22T00:32:15.642153Z"}
{"caller":"logutil.go:13","run service: enrolling host: query enrollment details: query enrollment details: could not query the extension manager client: EOF":"run launcher","severity":"info","ts":"2018-12-22T00:32:15.642251Z"}`

**Comment by calvinkim93** [comment]
Seems to be something with the launcher built by package-builter specifically. I am able to connect with the launcher in release (0.5.0) with no problem

**Comment by minamonk** [comment]
@calvinkim93 I get the same error when using version 0.6, however, when i use version 0.5.0, as you mentioned, I get the following error:
` kolide launcher","ts":"2019-01-04T12:53:25.784221057Z","version":"0.5.0"}
{"caller":"launcher.go:468","cert_pinning":false,"component":"launcher","grpc_secure":true,"level":"info","msg":"dialing grpc server","server":"<hostname>:443","tls_secure":true,"ts":"2019-01-04T12:53:25.795434316Z"}
{"caller":"launcher.go:337","component":"launcher","err":"enrolling host: transport error in enrollment: rpc error: code = FailedPrecondition desc = transport: received the unexpected content-type \"text/html; charset=utf-8\"","level":"info","ts":"2019-01-04T12:53:26.839201018Z"}`

Could you point me in the right direction?

**Comment by moivica** [comment]
Is this the asame issue?  

if it is then its not fixed 
```
{"caller":"updater.go:112","err":"enrolling host: query enrollment details, (even with retries): done trying: query enrollment details: could not query the extension manager client: read unix -\u003e/var/kolide-k2/k2device.kolide.com/osquery.sock: i/o timeout","msg":"updater interrupted","severity":"info","ts":"2022-04-07T09:09:41.925538Z"}```
