### ISSUE TITLE
Builds Dependent on being in GoPath

### ISSUE THREAD

**Issue by jakdept** [kolide/launcher#400]
I see that this project's switched to go mod (which is probably good) but then I also see that if you `make deps` in a checkout outside of the go path, you get an error:

```make
go run cmd/make/make.go -targets=generate-tuf
ts=2019-01-09T23:16:05.272633207Z caller=logutil.go:13 severity=info msg="Target Failed" err="opening notary config file: open /home/jack/go/src/github.com/kolide/launcher/tools/notary/config/config.json: no such file or directory" target=generate-tuf
exit status 1
Makefile:67: recipe for target 'generate' failed
make: *** [generate] Error 1
```

It looks like this is being kicked from /pkg/make/builder.go lines 282 and 283.

Mostly figured I'd point it out. Put this in my gopath instead and it seems to be working.

**Comment by directionless** [comment]
At least today, the launcher code itself is mostly path agnostic, but the autoupdate asset generation does some stuff based on full path.

**Comment by directionless** [comment]
Long since fixed
