### ISSUE TITLE
Windows Launcher .msi not Code Signed

### ISSUE THREAD

**Issue by 0xmachos** [kolide/launcher#411]
Unsure if this is the right place to report this so please correct me. 

I just downloaded the Kolide Launcher for Windows (`kolide-osquery-launcher.msi`). When I ran the `.msi` file I was presented with a SmartScreen warning. 

After i got past SmartScreen  I also had get through a UAC prompt warning me about a "an app from an unknown publisher".

Please can you start code signing the installer.

**Comment by Oneiroi** [comment]
https://docs.microsoft.com/en-us/windows/desktop/msi/sign-setup-exe-and-mysetup-msi (relevant documentation on this)

**Comment by directionless** [comment]
At this point, the Kolide SaaS downloadable launcher msi are signed.

If you have trouble with them, please reach out via support
