### ISSUE TITLE
Cannot generate Windows package with package-builder

### ISSUE THREAD

**Issue by WolfangAukang** [kolide/launcher#412]
Hey guys, so I'm trying to generate a package for Windows. I have osquery installed through Chocolatey and did the following steps:

```
cd $GOPATH/src/github.com/kolide/fleet
make deps
make package-builder
./build/package-builder.exe make --enroll_secret=my_secret \
> --insecure \
> --hostname=my.server.com:8990
could not generate packages: version detection: Failed to exec. Perhaps -- Can't autodetect while cross compiling. (): run command C:\Users\PEDROR~1\AppData\Local\Temp\package.packageRoot186823429\Launcher-launcher\bin\launcher.exe [-version], stderr=ts=2019-01-29T20:54:56.6547002Z caller=main_windows.go:69 severity=info err="Could not find osqueryd binary"
: exit status 1
```

I was looking at the `make --help`, but I don't see where can I specify the osqueryd binary path, as I can do with `launcher`. Is the package-builder for Windows working or is it still a work in progress?

Thank you

**Comment by szippy** [comment]
Hi WolfgangAukang,

I'm working on getting the package builder for windows working, but it's looking like there's still some work to be done here.

**Comment by WolfangAukang** [comment]
@szippy No problem, for now I will try to generate a service with Launcher and see if I can keep it running.

**Comment by directionless** [comment]
The windows packaging is undergoing a lot of change. That error indicates that `package_builder` was unable to detect the launcher version. Instead, you'll need to specific it with `--package_version `
