### ISSUE TITLE
Generating packages with package-builder for targets other than darwin fails

### ISSUE THREAD

**Issue by mbmy** [kolide/launcher#418]
**1. What version of launcher are you using (launcher --version)?**
`launcher - version 0.8.0
  branch: 	master
  revision: 	fa45344613462c7955543564efc258ba48e9856a
  build date: 	2019-02-07
  build user: 	seph (seph)
  go version: 	go1.11.5`
**2. What operating system are you using?** 
macOS 10.14.2
**3. What did you do?**
`./build/package-builder make -enroll_secret=“enrollsecret” -hostname=fleet.example.com:443 -targets="linux-systemd-deb" -debug`
**4. What did you expect to happen?**
Ability to build packages for alternate platforms (i.e. debian)
**5. What happened instead?**
`could not generate packages: version detection: Failed to exec. Perhaps -- Can't autodetect while cross compiling. (): run command /var/folders/f6/mcfrxynd42j2982thj6qhrm00000gn/T/package.packageRoot230576456/usr/local/kolide/bin/launcher [-version], stderr=: fork/exec /var/folders/f6/mcfrxynd42j2982thj6qhrm00000gn/T/package.packageRoot230576456/usr/local/kolide/bin/launcher: exec format error`

Unable to build packages for alternate targets other than darwin. Tested with deb, rpm, and Windows with similar result.

**Comment by directionless** [comment]
`package-builder` tries to exec `launcher -version` to tell what the package version should be. When you're packaging for another platform, this fails. You need to specify an appropriate `-package_version` flag.
