### ISSUE TITLE
Table Request: Add Slack Teams osquery-go table

### ISSUE THREAD

**Issue by FritzX6** [kolide/launcher#424]
The Slack desktop app stores a configuration file for associated teams in a JSON file at the following location on macOS devices:

```
~/Library/Application Support/Slack/storage/slack-teams
```

Example output of that file would be:

```js
{"T08V8ZM9C":{"name":"fritz","id":"U1MLUKL3X","team_id":"T08V8ZM9C","team_name":"osquery","team_url":"https://osquery.slack.com/","initials":"o","user_id":"U1MLUKL3X","hasValidSession":true,"locale":"en-US"...
```

Proposed schema for the new virtual table:
```
select * from kolide_slack_config where team_id = 'T08V8ZM9C';
+-----------+-----------+----------------------------+-----------+-------------+------------+
| team_name | team_id   | team_url                   | logged_in | user_handle | user_id    |
+-----------+-----------+----------------------------+-----------+-------------+------------+
| osquery   | T08V8ZM9C | https://osquery.slack.com/ | true      | fritz       | U1MLUKL3X  |
+-----------+-----------+----------------------------+-----------+-------------+------------+
```

Prior art for this sort of JSON parsing exists in the kolide_email_addresses table.

Per Privacy concerns from @terracatta: to keep from enumerating every team a user is associated with (potentially exposing private information they do not wish to share), the `team_id` field could be a **required WHERE clause**. This way organizations could supply their own known team_id to confirm their team-members are configured properly/logged-in, without the data-collection overreach.

**Comment by directionless** [comment]
At least on my machine, this is `~/Library/Containers/com.tinyspeck.slackmacgap/Data/Library/Application Support/Slack/storage/slack-teams` so this may need some additional updates to that find-file function

**Comment by directionless** [comment]
Implemented in https://github.com/kolide/launcher/pull/452
