### ISSUE TITLE
Error in make launcher on windows

### ISSUE THREAD

**Issue by cogmeta** [kolide/launcher#472]
make deps runs successfully but there is an error in make launcher.

\>make launcher
go run cmd/make/make.go -targets=launcher -linkstamp
\# github.com/kolide/launcher/cmd/launcher
cmd\launcher\control_windows.go:16:79: undefined: options
cmd\launcher\svc_windows.go:72:10: undefined: options
ts=2019-04-26T07:03:53.5822577Z caller=logutil.go:13 severity=info msg="Target Failed" err="exit status 2" target=launcher
exit status 1
make: *** [launcher] Error 1

**Comment by directionless** [comment]
Thanks for reporting this!

This looks like a effect of https://github.com/kolide/launcher/pull/466 I'll see about fixing it

**Comment by cogmeta** [comment]
Perfect! I tested new master branch and it works! Thank you.
