### ISSUE TITLE
Ability to turn off Control Subsystem

### ISSUE THREAD

**Issue by szippy** [kolide/launcher#496]
It would be nice if there was a way to compile launcher without the control subsystem. I'm concerned with the ability to launch a shell into any of our machines. It would be nice if there was a build flag that we could set to leave it out, and a way to verify that it wasn't included. 

Right now the control system can be enabled by either the --control flag, an environmental variable, or the flags file, but it would be better to be able to un-include it all together, and verify that it had been un-included.

**Comment by groob** [comment]
FWIW control can _only_ be enabled with the CLI flag and therefore a restart, there's no way to enable it remotely.

**Comment by rhuddleston** [comment]
It can also be set via ENV as well right e.g. KOLIDE_CONTROL?  I also assume everything can be set the the launcher.flags file?

**Comment by groob** [comment]
Environment and flags are parsed at the same time. There’s no difference other than how you prefer to type strings

**Comment by rhuddleston** [comment]
The difference is in how we can verify that it's off:

`SELECT p.pid, p.name, p.path, p.cmdline, e.key, e.value FROM processes p JOIN process_envs e ON p.pid = e.pid where name='launcher' and (cmdline like '%controL%' OR key LIKE '%CONTROL%');`

but if it can be in a file do we just look for /etc/launcher/launcher.flags or maybe it depends on how it was compiled which path that could be?

**Comment by directionless** [comment]
At this time, I don't want to pursue compile time options. 

Though the remote shell has been removed.
