### ISSUE TITLE
Duplication of hosts in kolide fleet

### ISSUE THREAD

**Issue by mareknejedly** [kolide/launcher#504]
Hello,

I have a problem with Kolide fleet. Once I connect from Kolide lanucher to the fleet, the connection works well. However once I go offline and go online again, it automatically start through systemd but in Kolide fleet it will create new host with same hostname, ip, mcadress etc.

Can you please advice how to remove this issue? This error does not happen if I use plain Osquery. 

Thanks a lot for your help.

Kind regards,

Marek

**Comment by zwass** [comment]
What is the command you are using to run Launcher? My guess would be that each Launcher instance is using a new database and therefore generating a new UUID and node key.

**Comment by mareknejedly** [comment]
Hi Zachary,

I am lunching it through systemd. Interesting is that if I do "systemctl stop launcher.service" and then I run "systemctl start lancher.service" it does not create new hosts. Only during the reboot of the whole host.
----
[Install]
WantedBy=multi-user.target


[Unit]
Description=The Kolide Launcher
After=network.service syslog.service

[Service]
ExecStart=/usr/bin/launcher \
  --hostname=172.20.10.10:8080 \
  --enroll_secret=zKBl2YKBGYDtsnYKkxB1eigzob+SnXxy \
  --autoupdate \
  --osqueryd_path=/usr/bin/osqueryd \
  --root_pem=/home/non-root/Documents/server.pem \
  --insecure
Restart=on-failure
RestartSec=3

[Install]
WantedBy=multi-user.target
---
Thanks for help!

Marek
