### ISSUE TITLE
Launcher update may leave windows service broken

### ISSUE THREAD

**Issue by directionless** [kolide/launcher#509]
Windows update support uses a two step copy. First the old exe is moved out of the way, then the new one is added. This creates a race condition. If something goes wrong moving the new binary into place, a future restart will leave the launcher service broken.

This can be seen by:
* An event log message in the System log, with the source `Service Control Manager` saying the service failed to start due to `The system cannot find the file specified`
* The installation directory is missing a `launcher.exe` but does have a populated `launcher.exe-staging`

The code in question should be in https://github.com/kolide/launcher/blob/4c0320d61d2b05fdd79bc32e905e2bf670937cfb/pkg/autoupdate/handler_windows.go

## Workarounds

You can recover a system by manually copying a launcher back into place. As administer:
```
cd ...
cp launcher.exe-staging\windows\launcher.exe .\
Start-Service LauncherXXXXX
```

**Comment by polak785** [comment]
This issue has not been fixed with Launcher Auto Update Process Version 2 ?

**Comment by directionless** [comment]
The underlying race conditions have been addressed, and this can now be closed.

**Comment by directionless** [comment]
@polak785 I don't understand the question you're asking.

**Comment by polak785** [comment]
@directionless I'm just asking if this issue as been fixed or not. Because I saw that this issue was created on 21 Aug 2019 and the rework of the autoupdate system (update v2) has been released on 18 Oct 2019 ;)

**Comment by directionless** [comment]
Yeah, Between the overhaul (v2) and some of the subsequent corruption checks, this shouldn't happen any more.
