### ISSUE TITLE
Unable to compile launcher due to broken apache deps

### ISSUE THREAD

**Issue by straffin** [kolide/launcher#522]
git.apache.org has been unavailable for two weeks and may not be coming back:
![image](https://user-images.githubusercontent.com/4968041/64648179-6ca2e900-d3e8-11e9-89ae-d8133588fdbb.png)
All references to git.apache.org in fleet, launcher, and any other code should be changed to use github.com/apache.
See [https://github.com/kolide/fleet/issues/2102](https://github.com/kolide/fleet/issues/2102) for more information.

**Comment by directionless** [comment]
This should have been fixed in https://github.com/kolide/launcher/pull/516 a couple days ago. What version are you seeing this with? (I'm going to close, but feel free to comment or reopen)

**Comment by straffin** [comment]
Derp! Sorry...assumed that since there was no issue, there was no solution. Will update my code and try again.

**Comment by directionless** [comment]
No worries!
