### ISSUE TITLE
Table Request: startup_security

### ISSUE THREAD

**Issue by FritzX6** [kolide/launcher#544]
What is being requested?
---
A new virtual table called `startup_security`

What is the background / purpose of this table?
---
Apple devices (especially those with T2 chips) have a variety of additional security measures that can be configured for pre-boot.

- [ ] EFI Firmware Password (boolean) 
- [x] ~Secure Boot (Full, Medium, No Security, N/A)~ **Addressed by:** https://github.com/osquery/osquery/pull/6053
- [x] ~External Boot (Disallowed, Allowed)~ **Addressed by:** https://github.com/osquery/osquery/pull/6053

Several administrators have asked for a way to enumerate these settings using osquery for their own compliance requirements.

![image](https://user-images.githubusercontent.com/931724/68952598-22ded200-078e-11ea-89c5-0619a1b39025.png)

How can this data be retrieved?
---
While these values are stored partially in nvram, they are inaccessible by querying the existing osquery `nvram` table. The values for each must be called discretely specifying the associated GUID.

For example:

```
➜  ~ nvram -p | grep Fritz               
good-samaritan-message	Hi Fritz
```
```
➜  ~ nvram -p | grep StartupManagerPolicy
➜  ~ nvram 5eeb160f-45fb-4ce9-b4e3-610359abf6f8:StartupManagerPolicy
5eeb160f-45fb-4ce9-b4e3-610359abf6f8:StartupManagerPolicy	%00
```
A clever user on the Jamf forums published a way to retrieve these GUID's: https://www.jamf.com/jamf-nation/discussions/29478/secure-boot-ea

These GUID's are static across devices (all devices use the same GUID's), and they can be found using the following method:
- Open a Terminal and run:
- ```sudo sysdiagnose```
- Expand the archive it creates
- Open the `securebootvariables.txt`

For simplicity's sake I have copied the output of my own `securebootvariables.txt` file below:
```
94b73556-2197-4702-82a8-3e1337dafbfb:ApChipID	%12%80%00%00
94b73556-2197-4702-82a8-3e1337dafbfb:ApBoardID	%0a%00%00%00
94b73556-2197-4702-82a8-3e1337dafbfb:ApSecurityDomain	%01%00%00%00
94b73556-2197-4702-82a8-3e1337dafbfb:ApProductionStatus	%01
94b73556-2197-4702-82a8-3e1337dafbfb:ApSecurityMode	%01
94b73556-2197-4702-82a8-3e1337dafbfb:EffectiveProductionStatus	%01
94b73556-2197-4702-82a8-3e1337dafbfb:EffectiveSecurityMode	%01
94b73556-2197-4702-82a8-3e1337dafbfb:HardwareModel	j137ap%00%00%00%00%00%00%00%00%00%00
94b73556-2197-4702-82a8-3e1337dafbfb:AppleSecureBootPolicy	%02
94b73556-2197-4702-82a8-3e1337dafbfb:AppleSecureBootFailureReason	%00
94b73556-2197-4702-82a8-3e1337dafbfb:AppleSecureBootWindowsPolicy	%00
5eeb160f-45fb-4ce9-b4e3-610359abf6f8:StartupManagerPolicy	%00
5eeb160f-45fb-4ce9-b4e3-610359abf6f8:StartupManagerFailureReason	%00
5eeb160f-45fb-4ce9-b4e3-610359abf6f8:AppleFailedBootVolumeUUID	%f2%09%9e%1b%16KIp%92%08/D%1ai%aa%d2
```
There is a larger amount of data present than what is proposed in this GitHub Issue but I would love to hear the thoughts of @groob or others who might advocate for its inclusion.

The two key/value pairs that we are concerned with at the moment are:
### Secure Boot:
```
94b73556-2197-4702-82a8-3e1337dafbfb:AppleSecureBootPolicy	%02
---
%02  = Full
%01  = Medium
%00  = Disabled
NULL = Not Applicable
```

### External Boot
```
5eeb160f-45fb-4ce9-b4e3-610359abf6f8:StartupManagerPolicy	%00
---
%00  = Disallowed
%03  = Allowed
NULL = Not Applicable
```
**Note:** Devices without T2 chips will not return data for these two settings (hence null values).

### EFI Password
So far as I have been able to determine, the EFI password state cannot be checked the same way as the other two options via nvram and must instead come from the output of the firmwarepasswd utility:
```
➜  ~ sudo /usr/sbin/firmwarepasswd -check                           
Password:
Password Enabled: No
```

What is the proposed output of this table?
---
```
osquery> SELECT * FROM startup_security
+--------------+-------------+---------------+
| efi_password | secure_boot | external_boot |
+--------------+-------------+---------------+
| enabled      | full        | disallowed    |
+--------------+-------------+---------------+
```

**Comment by directionless** [comment]
I believe this is handled by https://github.com/osquery/osquery/pull/6053 ?

**Comment by FritzX6** [comment]
@directionless Yep. I was waiting for the PR to go through review before closing the issue, but I can go ahead and do so now as it looks like it is likely to be merged.

![image](https://user-images.githubusercontent.com/931724/69020164-998ff100-0981-11ea-9f83-b0659813408a.png)

**Comment by FritzX6** [comment]
@directionless 
We were too hasty in our eagerness to close the issue. I recalled that the EFI Password status remains outstanding and so the issue still has unresolved items.
