### ISSUE TITLE
Package-Creator build: Wix toolkit location

### ISSUE THREAD

**Issue by defensivedepth** [kolide/launcher#546]
Currently the location of the wix toolkit is [hardcoded](https://github.com/kolide/launcher/blob/master/pkg/packagekit/wix/wix.go#L84)

The default install location for both the Chocolatey wix package & the installer from the wix website is ` C:\Program Files (x86)\WiX Toolset v3.11\` - 

The install location can be confirmed by checking the `WIX` environment variable.

The recommendation would be to use the `WIX` env variable rather than hardcoding the path.

**Comment by directionless** [comment]
I think mine landed there, as it's where the zip files distributed put them. But I'd be happy to have some kind of option for it. I've generally found windows environmental variables highly error prone, so would strongly prefer a command line flag.

As with the other command line flags, taking the value of the environmental variable as a default seems okay too.

**Comment by defensivedepth** [comment]
command line flag defaulted to the value of the env variable sounds like a great solution.

One note: the folder structure of `C:\Program Files (x86)\WiX Toolset v3.11\` includes a number of different directories, including `bin`, which is what package-creator needs - so you may need to concat `\bin` onto the end of the  value that you pull from the env variable.

**Comment by hilt86** [comment]
@directionless what do we need to make this happen?

**Comment by defensivedepth** [comment]
@directionless thanks for tackling this!
