### ISSUE TITLE
LUKS support incomplete in osquery for Linux FDE status

### ISSUE THREAD

**Issue by FritzX6** [kolide/launcher#567]
## What is the problem?

Encryption via LUKS is not always observable via osquery and causes machines to falsely report as being unencrypted. 

This is an ongoing problem which the osquery team attempted to deal with all the way back in 2015 in [osquery/osquery: Issue #993](https://github.com/osquery/osquery/issues/933):

>Spent way too much time debugging why FDE status reporting was flaky on my linux VM.
Turns out `libcryptsetup` calls into `libdevmapper` (part of libcryptsetup), which checks if it's being called as root, and only initializes the device context if it's called as root. Otherwise it returns an error: _"No such mapped device"._
>
>When it is being called as root, it returns status as expected.
>This isn't ideal, what do you suggest I do?

Unfortunately, they could not address it due to a `root` requirement. Which is documented in the Red Hat Issue Tracker: https://bugzilla.redhat.com/show_bug.cgi?id=1098714

## How can we address this?
Write an encryption table specifically for LUKS in Go.

Launcher runs by default as root and should be able to overcome this limitation allowing us to accurately report the encryption status of LUKS encrypted Linux devices.

### Running as a basic user
```shell
➜  ~  cryptsetup --debug status /dev/dm-0
# cryptsetup 1.6.6 processing "cryptsetup --debug status /dev/dm-0"
# Running command status.
# Installing SIGINT/SIGTERM handler.
# Unblocking interruption on signal.
# Initialising device-mapper backend library.
# /dev/mapper/control: open failed: Permission denied
# Failure to communicate with kernel device-mapper driver.
# Incompatible libdevmapper (unknown version) and kernel driver (unknown version).
Cannot initialize device-mapper, running as non-root user.
# Releasing device-mapper backend.
Command failed with code 22: Cannot initialize device-mapper, running as non-root user.
```

### Running as root:
```shell
➜  ~  sudo cryptsetup --debug status /dev/dm-0
# cryptsetup 1.6.6 processing "cryptsetup --debug status /dev/dm-0"
# Running command status.
# Installing SIGINT/SIGTERM handler.
# Unblocking interruption on signal.
# Initialising device-mapper backend library.
# dm version   OF   [16384] (*1)
# dm versions   OF   [16384] (*1)
# Detected dm-crypt version 1.13.0, dm-ioctl version 4.28.0.
# Device-mapper backend running with UDEV support enabled.
# dm status lvm  OF   [16384] (*1)
# Releasing device-mapper backend.
/dev/dm-0 is active and is in use.
# Allocating crypt device context by device /dev/dm-0.
# Initialising device-mapper backend library.
# dm status lvm  OF   [16384] (*1)
# Releasing device-mapper backend.
# Trying to open and read device /dev/sda2.
# Allocating crypt device /dev/sda2 context.
# Trying to open and read device /dev/sda2.
# Initialising device-mapper backend library.
# dm table lvm  OFW    [16384] (*1)
# Trying to open and read device /dev/sda2.
# Crypto backend (gcrypt 1.6.3) initialized.
# Detected kernel Linux 3.18.5-1-ARCH x86_64.
# Reading LUKS header of size 1024 from device /dev/sda2
```

**Comment by directionless** [comment]
I'm not sure what's going on here -- The linked bug implies osquery will detect correctly when run as root. And, when running under launcher it has the same uid. (eg: it'll be root if launcher is root)

**Comment by directionless** [comment]
Chatting in person, we don't think launcher can do anything osquery isn't already doing.

**Comment by ringerc** [comment]
For others who find this, LUKS uses `libcryptsetup` in https://github.com/osquery/osquery/commit/a972b1b0b0bc1bd1cd73335e68de634b44cea43b . This requires the ability to open the raw block device, it's doing much the same thing as the `cryptsetup` CLI tool.

I didn't find anywhere that LUKS exposes the cipher, mode etc in sysfs, procfs, or via systemd d-bus endpoints that could be interrograted by osqueryd. It'd be great to expose this info somehow, because osqueryd _really_ shouldn't have the right to open raw block devices.

**Comment by smlx** [comment]
Ah I only found this issue today! https://github.com/kolide/launcher/issues/1469 is related.

@ringerc a systemd resource control directive like this is enough for kolide's FDE checks. At least it is read-only (via eBPF filter).

```
DeviceAllow=/dev/mapper/nvme0n1p6_crypt r
```
