### ISSUE TITLE
Kolide Best Practices Table

### ISSUE THREAD

**Issue by marpaia** [kolide/launcher#57]
Master task to build out the `kolide_best_practices` table which is a single-row table with the following boolean columns on macOS:

- [ ] `automatic_updates_enabled`
- [x] `filevault_enabled`
- [x] `system_firewall_enabled`
- [x] `sip_configured`
- [x] `gatekeeper_enabled`
- [x] `password_required_from_screensaver`

The current implementation of the table exists at [`osquery/best_practices.go`](https://github.com/kolide/launcher/blob/master/osquery/best_practices.go).

**Comment by zwass** [comment]
Closing this issue as this table now exists. New column requests should go into new issues.
