### ISSUE TITLE
launcher update high CPU (100%)

### ISSUE THREAD

**Issue by MinhKMA** [kolide/launcher#600]
today, launcher update fail: 
(1) log: 
```
caller=level.go:63 level=error caller=findnew.go:194 fullBinaryPath="C:\\Program Files\\Kolide\\Launcher-launcher\\bin\\launcher.exe-updates\\1586310956\\launcher.exe" updateDir="C:\\Program Files\\Kolide\\Launcher-launcher\\bin\\launcher.exe-updates" binaryName=launcher.exe msg="not executable. Skipping" binary="C:\\Program Files\\Kolide\\Launcher-launcher\\bin\\launcher.exe-updates\\1586310956\\launcher.exe" reason="context deadline exceeded"
```

(2) image:

<img src="https://i.imgur.com/VaKh5al.png">

**Comment by directionless** [comment]
Hi @MinhKMA That looks like the beta release I pushed yesterday, which did have that bug. Are you using the beta channel? The current stable release is `0.11.9`.

While the beta has been removed, recovering is somewhat manual. To recover, you need to remove `C:\Program Files\Kolide\Launcher-launcher\bin\launcher.exe-updates` and let launcher restart. Windows won't let you remove a running binary from disk, so you probably need to move the `.exe` manually.
