### ISSUE TITLE
If you're using `package-builder` it defaults to downloading the last stable build from Kolide, **not** building launcher from source.

### ISSUE THREAD

**Issue by Samboy1990** [kolide/launcher#603]
If you're using `package-builder` it defaults to downloading the last stable build from Kolide, **not** building launcher from source.

But the appkit thing does look like there's some missing dependency. No part of this uses xcode. It's all pretty plain go (and cgo) with a make wrapper,

What OS are you running the build on? Anything weird?

_Originally posted by @directionless in https://github.com/kolide/launcher/issues/594#issuecomment-606802918_

**Comment by directionless** [comment]
Hi. You appear to be creating spam in these issues. Is this some kind of email issue?
