### ISSUE TITLE
problem for packages binary using pakage-builder in windows

### ISSUE THREAD

**Issue by avelasquez4** [kolide/launcher#611]
problem for packages as indicated in the guide and not being able to compile the laucher to create the binary you can help me

**Comment by directionless** [comment]
This does not contain an error, or anything to help you with.

You can compile `launcher` and `package-builder` using a standard go toolchain and `make`. I usually cross compile from linux.

You can also download compiled launcher from github, or the kolide update server.

We use GitHub for bug tracking. There is some amount of community support on the #kolide channel osquery slack. You can join via https://osquery-slack.herokuapp.com/
