### ISSUE TITLE
package-builder for ARM target

### ISSUE THREAD

**Issue by rmspeers** [kolide/launcher#640]
I have successfully built using package-builder for Windows, Linux x86/64, and macOS, however I am looking to do a linux-systemd-rpm for an ARM target (RaspberryPi). I do not see a way to cross-compile for ARM here -- could you point me in the right direction?

**Comment by directionless** [comment]
Neither osquery, nor launcher will run on that platform. 

With the upcoming Apple Silicon it may be simpler to port to it.

**Comment by rmspeers** [comment]
Could it not be cross compiled in a Docker, for example, targeting ARM?

**Comment by directionless** [comment]
It it not a question of build machines. AFAIK osquery does not currently support ARM or 32bit build. This may change when https://github.com/osquery/osquery/pull/6612 and https://github.com/osquery/osquery/pull/6543 merge.

**Comment by directionless** [comment]
This is not something currently being worked on
