### ISSUE TITLE
MacOS newsyslog lograte restart launcher, bug extension not quit

### ISSUE THREAD

**Issue by sdl9i2** [kolide/launcher#671]
![5485BDAF-201E-4DE5-ACB5-CCF5A0D9E9C3](https://user-images.githubusercontent.com/16425310/97657011-d2967800-1aa3-11eb-9acb-72f3be87dab9.png)

lograte every rate log, launcher will restart , but extension not quit

**Comment by niu-b-long** [comment]
this https://github.com/kolide/launcher/pull/342 mr have a bug, monitorForParent get a time ticker , then quit.

    for {
        select {
        case <-ticker.C:
            f()
        }

**Comment by directionless** [comment]
`osquery-extension` is no longer part of launcher
