### ISSUE TITLE
how launcher autoupdate osquery-extension.ext, not find any document for this

### ISSUE THREAD

**Issue by niu-b-long** [kolide/launcher#672]
I m not find some document for launcher update osquery-extension; combine with launcher or osqueryd as *.tar.gz , 
launcher or osqueryd is updated, buy extension is not.

**Comment by directionless** [comment]
Launcher does not currently update `osquery-extension`. But, that extension doesn't really do anything, it's a no-op that exists for how osquery handles extensions and sockets.
