### ISSUE TITLE
New Table Request: fc-list exec

### ISSUE THREAD

**Issue by FritzX6** [kolide/launcher#685]
### What is the purpose of this table?
`fc-list` is a binary which lists all installed fonts on a device. This would allow a user to query whether a given font is installed in Font Book.

### What format is the data?
Comma Separated and New Lines eg.
```
> fc-list
/Users/fritz-imac/Library/Fonts/Knockout-HTF70-FullWelterwt.otf: Knockout,Knockout HTF70\-FullWelterwt:style=HTF70-FullWelterwt,Regular
/Users/fritz-imac/Library/Fonts/Mark Simonson - Proxima Soft ExCn Black.ttf: Proxima Soft Extra Condensed,Proxima Soft ExCn Black:style=Black,Regular
/Users/fritz-imac/Library/Fonts/NeutraText-LightSCItalic.otf: Neutra Text,Neutra Text Light SC:style=Light SC Italic,Italic
/Users/fritz-imac/Library/Fonts/Mark Simonson - Proxima Soft ExCn Extrabold It.ttf: Proxima Soft Extra Condensed,Proxima Soft ExCn Extrabold:style=Extrabold Italic,Italic
/Users/fritz-imac/Library/Fonts/MuseoSans-300Italic.otf: Museo Sans,Museo Sans 300:style=300 Italic,Italic
```

### What options does this exec have that we could pass?
The `-f` format flag can be passed to limit output:
```
> fc-list -f '%{file}\n'
/Users/fritz-imac/Library/Fonts/ITCAvantGardeStd-XLtCnObl.otf
/Users/fritz-imac/Library/Fonts/GoogleSans-Bold.ttf
/Users/fritz-imac/Library/Fonts/NeutraText-BookItalicFrac.otf
/Users/fritz-imac/Library/Fonts/AvenirNextLTPro-UltLtCn.otf
/Users/fritz-imac/Library/Fonts/CrimsonText-Semibold.ttf
```

### Why don't we get this a different way like System Profiler?
Unfortunately the output from `SPFontsDataType` has proven incomplete in terms of what it is able to collect.

**Comment by directionless** [comment]
What information do we want out of this? What would we want in that format?

**Comment by directionless** [comment]
I haven't been able to find a complete list of keys, but at a first pass we can use 
```
fc-list --format 'file: %{file}\nfamily: %{family}\nstyle:%{style}\n'
```

with the nmcli parsers.

fc-list is a cross platform tool as well

**Comment by directionless** [comment]
I think we decided we didn't want this.
