### ISSUE TITLE
Launcher service creating cross-thread hangs when unable to connect to fleet host.

### ISSUE THREAD

**Issue by ANDERSONTECHWERKS** [kolide/launcher#725]
**What version of launcher are you using (launcher --version)?**
Version 0.11.19
    
    **What operating system are you using?**
Windows 10 Education Edition
    
    **What did you do?**
Turned off my security onion instance, which launcher was connecting to, and acts as my "Fleet host". 

 Was experiencing lock-ups on a different program (TexStudio) due to a cross-thread hang, and while troubleshooting - noticed that launcher was aggressively spamming my Windows Event Viewer log. Stopped the launcher service, and have not had TexStudio hang on me due to cross-thread since. Do not believe this is some niche issue with TexStudio.
 
I'm a novice programmer, and I'm uncertain whether the launcher application opens a new thread in certain cases - but perhaps it could cause a cross-thread in certain situations? Apologies for any sloppiness. This is my first time really writing up an issue.
    
    **What did you expect to happen?**
Expected launcher to fail silently, or at least - with limited log entries.

    **What happened instead?**

There were > 100 launcher log entries in my windows event viewer, with entries such as (Sanitizing data I'm uncertain about sharing, for safety) :

"caller=log.go:124 ts=*sanitized* caller=level.go:63 level=info caller=log.go:69 component=osquery level=stderr msg=*sanitized* processes.cpp:366] Failed to lookup path information for process 2128" caller=processes.cpp:366"

"caller=log.go:124 ts=2021-03-24T00:05:57.874916Z caller=level.go:63 level=info caller=log.go:69 component=osquery level=stderr msg="*sanitized*  processes.cpp:338] Failed to get PEB UPP for 2128 with *sanitized* processes.cpp:380] Failed to get cwd for 2128 with*sanitized* processes.cpp:272] Failed to get PEB UPP for 2128 with 0" caller=processes.cpp:338"

These > 100 entries were all populated within a span of the same **second**.

Can provide more information, or sanitized logs, if necessary

**Comment by directionless** [comment]
Hi! Thanks so much for reporting this. I'm not sure I understand all the details.

> Turned off my security onion instance, which launcher was connecting to, and acts as my "Fleet host".

What does this mean? Does that mean you turned off your fleet instances, and accordingly the launcher was stranded?

> "caller=log.go:124 ts=sanitized caller=level.go:63 level=info caller=log.go:69 component=osquery level=stderr msg=sanitized processes.cpp:366] Failed to lookup path information for process 2128" caller=processes.cpp:366"

That's an error emitted by osquery. This particular one is unimportant, and I think unrelated. Launcher has generally taken the stance of passing along osquery errors, do you think it should filter them?

Are the other messages in your logs similar to those, or different?

Can you include your launcher config files? I am wondering if you set debug

**Comment by ANDERSONTECHWERKS** [comment]
> 
> 
> Hi! Thanks so much for reporting this. I'm not sure I understand all the details.
> 
> > Turned off my security onion instance, which launcher was connecting to, and acts as my "Fleet host".
> 
> What does this mean? Does that mean you turned off your fleet instances, and accordingly the launcher was stranded?
> 
That's correct! By "Fleet instances", I'm assuming you are describing the central host that all my launcher clients report to.
> > "caller=log.go:124 ts=sanitized caller=level.go:63 level=info caller=log.go:69 component=osquery level=stderr msg=sanitized processes.cpp:366] Failed to lookup path information for process 2128" caller=processes.cpp:366"
> 
> That's an error emitted by osquery. This particular one is unimportant, and I think unrelated. Launcher has generally taken the stance of passing along osquery errors, do you think it should filter them?
While this one may be unrelated, I have a log full of roughly ~100+ messages that were populated as soon as I turned off my security onion host (What should I call the central server that my launcher instances report to?).
> 
> Are the other messages in your logs similar to those, or different?
> 
There seems to be an assortment of log entries. Believe the relevant ones are mentioning something along the lines of "all SubConns are in TransientFailure, latest connection error: connection error... And it goes on to describe issues connecting to my security onion host.

> Can you include your launcher config files? I am wondering if you set debug
Just to ensure that I'm giving you the right thing - what would the specific file you'd like to look at be on a Windows machine?

**Comment by directionless** [comment]
> What should I call the central server that my launcher instances report to?

In osquery parlance, that's a TLS server. or sometimes fleet manager. "Fleet" is also the name of a TLS server that Kolide opened sourced, and no longer maintains. I assume you're running some version of fleet. But it's probably not so important....

I think what you're describing is that when the central server goes away, launcher sends a lot of logs into the event log, maybe too many. And that you also see a cross-thread hang, perhaps related to the messages being sent to event logs, or perhaps not. Correct?

I'm not familiar with the cross-thread hangs, and am unsure of what the likely causes there are. 

It's a bit hard to diagnose much without the log and config file. I'd certainly believe there are too many things being logged, but I'd need to see more to understand. If you're comfortable sharing the log file with me, but not github readers, feel free to email me at `seph@kolide.co`

**Comment by ANDERSONTECHWERKS** [comment]
Yes, the Fleet Manager is what I'm describing!

> I think what you're describing is that when the central server goes away, launcher sends a lot of logs into the event log, maybe too many. And that you also see a cross-thread hang, perhaps related to the messages being sent to event logs, or perhaps not. Correct?

This is correct!

Apologies for the lag-time (I'm a full time student), but I'll try to get that config file and log to you once I get some downtime and am able to review the file for anything sensitive. Apologies for the paranoia, but I have to ask: You're alright if I clear out any keys from those files, right?

**Comment by directionless** [comment]
Yes, feel free to redact any keys. 

The launcher config file may have a secret, but more likely points to a separate secret file. It will have a hostname in it.
