### ISSUE TITLE
Missing a "Getting Started Guide"

### ISSUE THREAD

**Issue by su0pfi5h** [kolide/launcher#727]
Hi,

first of, I dont have any proir knowlege to how osquery or Kolide work in the background.
Even now, after reading all documents I was able to find online, it is still a big mystery to me how to deploy it successfully. 
Maby I am an idiot, but I hope not. ;)

However, I was able to succesfuly install the Kolide Fleet Manger (I know there is a newer tool, but I do this just for fun and didnt want to buy a product I dont know anything about), and started multiple VMs to deploy the agent for testing purposes. 
But the steps from creating the agent to mass deploying/autoupdating it to clients is still unclear to me.

Step by Step report:
- I using Windows as an OS
- download [launcher](https://github.com/kolide/launcher) via git clone command
- switch to version v0.11.19 because master wouldnt build with docker
- build via:  ```docker build -t launcher .```
- open it via : ```docker run --rm -it launcher bash```
- run: ```make package-builder-windows && ls build/windows/package-builder.exe```
- copied the ```.exe``` outside into my Windows Maschine
- download ```wix``` as ```ZIP```-file, extracted into  into ```C:\wix311```, whats seems to be the right path
- run: ```./build/package-builder make   --hostname=<fleeturl>:<fleetport>  --enroll_secret=<secret> --autoupdate=true```
->successfully created a ```.msi``` launcher
- copied the msi into my VM and installed it

Issues:
- still nothing shows up in my Fleet
- i couldn't find any debug options for the launcher, like the osqueryd's tls_dump, etc.
- how do i utilize the updater function? For example if I want to install add an extension later on.

After spending over a week to fix this issues myself, now I hope that someone with experience could mabye help me!

**Comment by directionless** [comment]
Hi! It sounds like you're looking for a getting started guide to using osquery (and perhaps launcher) to monitor your machines.  While you might run osquery standalone, launcher is designed to work with a TLS server. Launcher cannot work without a server component. I would expect any documentation to be specific to the server side.

As you commented, Kolide is no longer maintaining Fleet. For details, see the readme at https://github.com/kolide/fleet

Launcher should build under docker, though I would generally recommend downloading the build releases from github -- https://github.com/kolide/launcher/releases/
