### ISSUE TITLE
Support firefox's preferences

### ISSUE THREAD

**Issue by directionless** [kolide/launcher#730]
Firefox stores its preferences in a `prefs.js` file. Despite the name, this is not javascript. It would be nice to be able to parse these.

Some info:
* https://blog.mozilla.org/nnethercote/2018/03/09/a-new-preferences-parser-for-firefox/
* https://searchfox.org/mozilla-central/source/modules/libpref/parser/src/lib.rs
* https://firefox-source-docs.mozilla.org/modules/libpref/index.html
* https://github.com/hansmi/go-mozpref

**Comment by em-hill** [comment]
When this is released, please let Signal FT know: 
https://app.intercom.com/a/inbox/n62vrvsb/inbox/view/32785/conversation/27252679467
