### ISSUE TITLE
Missing ssh-sk support in `kolide_ssh_keys`

### ISSUE THREAD

**Issue by directionless** [kolide/launcher#758]
I'm starting to hear about ssh-sk keys, and this is not something we can parse in `kolide_ssh_keys`. The underlying key type is (a) based on hardware keys and (b) not supported in apple's ssh. (need brew's)

I don't have enough of a local test case, but my suspicion, is that I'll need to parse this from the public side. I'm not yet sure how to handle reconciliation between public and private. It may make sense to create a separate table for public and private keys. Or simply return a column with that info.

**Comment by asinanis** [comment]
Just adding this so I can close the Intercom ticket for now:
https://app.intercom.com/a/apps/n62vrvsb/inbox/inbox/all/conversations/27252684079

**Comment by directionless** [comment]
I'm starting to dig into this.

`kolide_ssh_keys` is long deprecated, We should remove it. 

Tinkering with a yubikey, and using it to create some resident keys, it still gives me the option to encrypt them. So I think there are four possible states: [disk|hardware] [encrypted|unencrypted]

I don't know how common it is to encrypt keys stored in hardware, but I think I would not want to misrepresent that. As is, this table appears to correctly convey that state.
