### ISSUE TITLE
osqueryd is not statically linked

### ISSUE THREAD

**Issue by danderson** [kolide/launcher#770]
I'm trying to get Kolide working on NixOS, which does not store dynamic libraries the same as most linux distros. The osqueryd provided in the kolide enrolment bundle is not statically linked, despite the claim in README.md (`Osquery is statically linked and that allows for the easy bundling and distribution of capabilities.`).

```
$ ldd osqueryd
	linux-vdso.so.1 (0x00007fff36f32000)
	libdl.so.2 => /nix/store/jsp3h3wpzc842j0rz61m5ly71ak6qgdn-glibc-2.32-54/lib/libdl.so.2 (0x00007f5912c0b000)
	libresolv.so.2 => /nix/store/jsp3h3wpzc842j0rz61m5ly71ak6qgdn-glibc-2.32-54/lib/libresolv.so.2 (0x00007f5912bf3000)
	libz.so.1 => not found
	libpthread.so.0 => /nix/store/jsp3h3wpzc842j0rz61m5ly71ak6qgdn-glibc-2.32-54/lib/libpthread.so.0 (0x00007f5912bd2000)
	libm.so.6 => /nix/store/jsp3h3wpzc842j0rz61m5ly71ak6qgdn-glibc-2.32-54/lib/libm.so.6 (0x00007f5912a8f000)
	librt.so.1 => /nix/store/jsp3h3wpzc842j0rz61m5ly71ak6qgdn-glibc-2.32-54/lib/librt.so.1 (0x00007f5912a84000)
	libc.so.6 => /nix/store/jsp3h3wpzc842j0rz61m5ly71ak6qgdn-glibc-2.32-54/lib/libc.so.6 (0x00007f59128c1000)
	/lib64/ld-linux-x86-64.so.2 => /nix/store/jsp3h3wpzc842j0rz61m5ly71ak6qgdn-glibc-2.32-54/lib64/ld-linux-x86-64.so.2 (0x00007f59158a8000)
```

For various reasons, this means that the autoupdate functionality will routinely break and fail to launch osqueryd after updating it, and that it's hard to adapt kolide's enrolment bundles to run on NixOS.

It sounds like the intention was to statically link osqueryd. If so, could you fix? The other binaries in the enrolment bundle are indeed fully static, so it's just osqueryd that's falling short.

**Comment by directionless** [comment]
Hi @danderson! Kolide ships the osqueryd as distributed by The Osquery Foundation.

You're right, it's not wholly static. It's mostly static. I'm under the impression that statically linking to glibc is strong discouraged, and may not work at all. 

I think this is clearly a bug in our README.

I'n not familiar enough with NixOS to know if there's a good pattern to use here. Is there a way we can make this work?

**Comment by danderson** [comment]
I got something working, but it requires patching the binary to help it find the libraries. Sounds like it's WAI from your perspective, so I'll go off and see if we can make Kolide work in spite of this. Thanks.

**Comment by directionless** [comment]
Kolide isn't going to move away from the official osquery builds. But, I'm interesting in seeing if we can get it working. So, to that end, if there's something inside osquery to make this easier in NixOS, I'm happy to pursue that.

Similarly, if there's something we can do inside launcher, I'm also happy to look at that. 

I know there's going to be some other issue with how the auto update stuff is managed -- it assumes it can write to a path akin to the install path.

**Comment by danderson** [comment]
I have things mostly working now. NixOS presents two challenges for Kolide:
 - There is no /lib or /usr/lib, binaries must explicitly reference exact paths in /nix/store/<package hash>/lib. So the osqueryd binary cannot start out of the box.
 - Automatic updating means the binaries must be writable, I presume (is it both launcher and osqueryd, or just osqueryd?). This means we can't package Kolide as a normal Nix package, because those are read-only.

I was able to work around this by manually unpacking the .deb Kolide provided, placing the binaries and config under /var/kolide-k2 (so code+config+state is all in one directory), editing the launcher flags to set the right paths, then using Nix's FHS wrapper to construct a bespoke environment in which launcher runs - one where regular dynamic linking works. The Nix FHS wrapper masks both /etc and /usr from the parent filesystem, which is why I had to go lump everything into /var/kolide-k2.

I'm still trying to figure out how to make this less hacky, and once I do I'll document it somewhere online. In the meantime, you're welcome to close this issue, since osqueryd's build seems to be working as intended.

**Comment by directionless** [comment]
> * Automatic updating means the binaries must be writable, I presume (is it both launcher and osqueryd, or just osqueryd?). This means we can't package Kolide as a normal Nix package, because those are read-only.

It's a bit weirder -- The distributed binaries aren't updated in place. Instead an updates directory is created (on my mac, it's `/usr/local/kolide-k2/bin/launcher-updates`) and updates are left there timestamped. This path was originally chosen to allow a binary to find itself before reading any configuration files. I shouldn't be too hard to accept an ENV to override it though.

Oh, I can ship you a tarball just as easily as a deb or rpm.

**Comment by danderson** [comment]
Gotcha. I didn't find a good way of keeping /usr/local/kolide-k2 mapped in the FHS env, so an envvar to set the update location would be good (or alternatively, compute the update dir location based on the launcher binary's location, so that it moves with the launcher binary).

Having tarballs as an option in the enrolment process would be handy, but I assume there's not much call for that. Extracting from a .deb isn't too hard, so unless you have strong reasons to provide a tarball otherwise, I wouldn't bother.

**Comment by directionless** [comment]
> Gotcha. I didn't find a good way of keeping /usr/local/kolide-k2 mapped in the FHS env, so an envvar to set the update location would be good (or alternatively, compute the update dir location based on the launcher binary's location, so that it moves with the launcher binary).

It is calculated based on the path of the running executable. So it should be fine here. 

> Having tarballs as an option in the enrollment process would be handy, but I assume there's not much call for that. Extracting from a .deb isn't too hard, so unless you have strong reasons to provide a tarball otherwise, I wouldn't bother.

Okay! It's an option if you ever need it

**Comment by znewman01** [comment]
This feels similar enough to https://github.com/kolide/launcher/issues/638 that I'd consider marking them duplicates. Both are basically just saying "osquery autoupdate doesn't really work on NixOS."

We have two approaches forward that I can see:

1. Disable autoupdates on NixOS.
2. Support autoupdates on NixOS.

To be honest, I'm inclined towards (1). I understand the security benefits of autoupdating software (especially when it's all signed using TUF—very cool!) but this is in tension with the reproducibility goals of NixOS. I don't expect any upstream support for this, though.

Maybe the best thing to do is support both: in the NixOS configuration, users could choose between autoupdating using a slightly-cleaned-up version of the tricks mentioned earlier in this issue, or pinning their osquery.

Tangent: if you pin osquery, can we still get some of the benefits of TUF? It's possible, in theory: the updater could check that your pinned osquery corresponds to a valid Kolide-provided one on startup. In practice, however, I think this falls over: Nix would be building osquery from source, and probably linking against different libraries.

**Comment by directionless** [comment]
@znewman01 This and #638 are different ways launcher doesn't work on Nix. #896 is an overhead issue.

This issue was specific to linking. Discussion about autoupdate should be in #638. I'll answer over there

**Comment by directionless** [comment]
I'm going to close this. Osquery cannot be more statically linked, and there are some other issues relating to how to handle osquery in nix.
