### ISSUE TITLE
query_target.go causes fetching target memberships error with v0.11.22 and osqueryi version 5.0.1 (Mac)

### ISSUE THREAD

**Issue by mcha-sq** [kolide/launcher#777]
We got an error query_target.go like the following.

{"caller":"query_target.go:75","err":"fetching target memberships: rpc error: code = Unavailable desc = Bad Gateway: HTTP status code 502; transport: received the unexpected content-type \"text/html; charset=UTF-8\"","msg":"updating kolide_target_membership data","severity":"error","ts":"2021-11-24T05:32:09.863419Z"}

This error got triggered in updateTargetMemberships function like the following.

func (qtu *QueryTargetUpdater) updateTargetMemberships(ctx context.Context) error {
	nodeKey, err := osquery.NodeKeyFromDB(qtu.db)
	if err != nil {
		return errors.Wrap(err, "getting node key from db")
	}

	resp, err := qtu.targetClient.GetTargets(ctx, &qt.GetTargetsRequest{NodeKey: nodeKey})
	if err != nil {
		return errors.Wrap(err, "fetching target memberships")
	}

**Comment by directionless** [comment]
This sounds like part of the control server functionality? How are you using that?

**Comment by directionless** [comment]
This code has changed
