### ISSUE TITLE
Launcher, Rosetta, and macos 12.1

### ISSUE THREAD

**Issue by directionless** [kolide/launcher#779]
After the 12.1 upgrade, sometimes launcher fails to start. Digging into the logs, I see:
```
{"binary":"/usr/local/kolide-k2/bin/osqueryd-updates/1638566429/osqueryd","binaryName":"osqueryd","caller":"findnew.go:207","fullBinaryPath":"/usr/local/kolide-k2/bin/osqueryd","msg":"not executable. Skipping","reason":"fork/exec /usr/local/kolide-k2/bin/osqueryd-updates/1638566429/osqueryd: bad CPU type in executable","severity":"error","ts":"2021-12-14T13:37:11.85382Z","updateDir":"/usr/local/kolide-k2/bin/osqueryd-updates"}
```

Notable there, is `bad CPU type in executable` and my suspicion is that launcher is starting before Rosetta, and failing to start osquery. Obviously one fix is to ship an m1 osquery (That PR is in flight) But this raises some other questions.

Namely, either launcher should retry until it succeeds, or launcher should exit and let launchd restart it. Need to understand what happens instead

**Comment by asinanis** [comment]
Alert customer: https://app.intercom.com/a/apps/n62vrvsb/inbox/inbox/all/conversations/27252694997

**Comment by directionless** [comment]
As of 12.1, there is no longer a rosetta component.
