### ISSUE TITLE
Support running without processes table enabled

### ISSUE THREAD

**Issue by ulf5** [kolide/launcher#794]
This [query](https://github.com/kolide/launcher/blob/8fd5171dcda83647ec1e6ac7601fff7fe224cce8/cmd/launcher/flare.go#L226) seems to be what is preventing this from running without the processes osquery table enabled.

I have been trying to run the launcher with `osquery_flag enable_tables=<minimal_list_of_tables>` to only provide the minimum amount of data to pass the checks in kolide and it would be great if I could turn off the processes table also!

**Comment by directionless** [comment]
That code path is not executed. It's part of a manual operation that isn't exposed.

Launcher does not depend on that table, however osquery itself requires the processes table, it's part of how tracks it's state.
