### ISSUE TITLE
We should run codesigning from GitHub actions

### ISSUE THREAD

**Issue by directionless** [kolide/launcher#825]
With the addition of universal builds (#773), we should bring in codesigning. This will need:

* [x] macOS codesigning. Some weirdness around keychain management. There's likely prior art
* [x] macOS submit for notarization. Probably don't need to wait for a result, but we should record the uuid
* [x] windows codesigning. Same

Possibly this should be run from a private repo (as we do for `osquery`).

**Comment by James-Pickett** [comment]
Read this article for MacOS codesigning in GH actions, might be useful https://www.kencochrane.com/2020/08/01/build-and-sign-golang-binaries-for-macos-with-github-actions/

**Comment by directionless** [comment]
This work is done
