### ISSUE TITLE
Replace `altool` exec with `notarytool` or the new rest API

### ISSUE THREAD

**Issue by directionless** [kolide/launcher#836]
During WWDC22 Apple [announced](https://developer.apple.com/videos/play/wwdc2022/10109) that there's a new [rest API for notarization](https://developer.apple.com/documentation/notaryapi). This is exciting, and it will let is replace the shell exec in [applenotarization.go](https://github.com/kolide/launcher/blob/eb7667d4b2a24c8cb497855331492876466e4204/pkg/packagekit/applenotarization/applenotarization.go) with something nicer. 

Not yet clear if we should:
1. replace with a shell exec of `altool`
2. Write something against that API (and also pull in S3)
3. See if someone else has a nice implementation 
4. Maybe `relic` will do something, and then we can cross compile and sign for macOS?

At least today, I'm most curious about (2) and (4), but happy to wait a couple weeks to see what appears

**Comment by directionless** [comment]
This work was done

**Comment by RebeccaMahany** [comment]
Completed in https://github.com/kolide/launcher/pull/1258 while working on https://github.com/kolide/launcher/issues/1257
