### ISSUE TITLE
[Windows] Extension Path doest not exists

### ISSUE THREAD

**Issue by estebanramos** [kolide/launcher#852]
I'm currently having this error
`{"caller":"launcher.go:133","err":"launching osquery instance: starting instance: could not calculate osquery file paths: extension path does not exist: C:\\Program Files\\Kolide\\Launcher-launcher\\bin\\osquery-extension.exe: CreateFile C:\\Program Files\\Kolide\\Launcher-launcher\\bin\\osquery-extension.exe: El sistema no puede encontrar el archivo especificado.","level":"info","msg":"interrupted","ts":"2022-08-02T16:42:40.1333351Z"}`

Here's my build command
`.\build\package-builder.exe make --hostname osquery.dpsit.gba.gob.ar:443 --enroll_secret ******** --targets windows-service-msi --insecure  --output_dir .`

**Comment by directionless** [comment]
Chatting on slack, I'm pretty sure this  is because package-builder is from the HEAD of the repo (0.12.1), but it downloads the stable launcher (0.11.26) and that difference spans the removal of `osquery-extension`.

I've just bumped 0.12.1 to stable, which might fix it.

**Comment by directionless** [comment]
Sounds like it's resolves with 0.12.1
