### ISSUE TITLE
go v1.19: pkg/autoupdate/autoupdate.go:184:74: undefined: AssetDir

### ISSUE THREAD

**Issue by tstromberg** [kolide/launcher#866]
When running `make` with `GNU Make 4.3` and `go1.19`:

```
go run cmd/make/make.go -targets=launcher -linkstamp   
# github.com/kolide/launcher/pkg/autoupdate
pkg/autoupdate/autoupdate.go:184:74: undefined: AssetDir
pkg/autoupdate/autoupdate.go:216:18: undefined: Asset
ts=2022-08-25T18:56:42.508627733Z caller=logutil.go:13 severity=info msg="Target Failed" err="exit status 2" target=launcher
exit status 1
make: *** [Makefile:45: build_launcher] Error 1
```

I can't tell if this is due to the `make` steps being underdefined or incompatibility with go v1.19. I know that `go-bindata` is less attractive than it used to be, now that the same functionality is bundled into Go using the `embed` API.

**Comment by tstromberg** [comment]
You can probably close this after documenting the instructions for building it - I took a look at the Dockerfile, and it appears that the correct steps are:

```
make deps
make all
```

**Comment by directionless** [comment]
Yes, correct -- it needed a `make deps`. Sorry for the confusion
