### ISSUE TITLE
Table Request: mdfind equivalent for Windows 'windows_search'

### ISSUE THREAD

**Issue by FritzX6** [kolide/launcher#898]
## What is being requested?

A new table called `windows_search`

We are often asked to search for files on Windows devices using similar capabilities to the macOS platforms `mdfind` table. It would be great to build something on top of the Windows Search API:

https://learn.microsoft.com/en-us/windows/win32/search/-search-sql-windowssearch-entry

**Comment by directionless** [comment]
Merged in osquery https://github.com/osquery/osquery/pull/7990
