### ISSUE TITLE
Table for `xfconf`

### ISSUE THREAD

**Issue by directionless** [kolide/launcher#928]
While digging into a xfce` based linux device, we noticed that it does not use `gsettings`. This is, of course, not a surprise.

But, it looks like there's a `xfconf-query` command. So we ought be able to make a table exposing that info.

I haven't done much research. Maybe the data is stored somewhere we can access it directly.

**Comment by RebeccaMahany** [comment]
It looks like we could read from the config files: `~/.config/xfce4/xfconf/xfce/perchannel/xml/*.xml`. I don't know whether this is preferable to running `xfconf-query` a bunch -- it looks like we have dataflatten support for xml, so maybe that's simpler.

**Comment by directionless** [comment]
I don't have a well considered answer for `kolide_xm` vs parsing `xfconf-query`. Thinking aloud...

* For `gsettings`, I couldn't figure out how to do it without an exec. Parts seemed to come down to `dbus` and and it looked hard. While xfconf is not gsettings, I assumed it would be similarly hard and didn't dig too deeply
* Generally, exec it's great. Reading data files feels better
* But getting the application specific rules feels hard. We can do simple merges, but is there more nuance? (Like default values)
* And will it change?

I think we could go either way -- use `kolide_xml`, or write a table that execs `xfconf-query`. We could use the former until we see enough of a need for the later. Or we can do the latter because it's fun. 🤷
