### ISSUE TITLE
Table for server writable data

### ISSUE THREAD

**Issue by directionless** [kolide/launcher#936]
We keep wanting to be able to have some kind of server writable data inside launcher. This should manifest as a table, which can then be joined against or used in decorators. I'm pretty sure this should be an EAV style table. Likely with columns `entity`, `attribute`, and `value`. 

We have some fragments of this work, I envisioned something like this ages back and it was implemented as [`kolide_targetting`](https://github.com/kolide/launcher/blob/8f2726c262c56849c530b0e6db9c070df169cb57/pkg/osquery/table/kolide_target_membership.go). But, that table has several flaws, and should be revisited. A very rough set of tasks:

* [ ] rename/replace `kolide_target_membership` to something like `kolide_metadata` or `kolide_server_data` or ???
* [ ] convert table from one column, to three columns -- `entity`, `attribute`, `value` (or, if we're stuck on types, maybe `entity`, `attribute`, `string`, and `int`)
* [ ] Remove the GRPC interface to this table
* [ ] This data should come from a new rocksdb bucket. It will be updated by the control server

**Comment by James-Pickett** [comment]
> Remove the GRPC interface to this table

Does removing GRPC imply that we'll remove all the protobuf references as well? I'm not clear on how intertwined the 2 are. If so, the would it just be vanilla json?

**Comment by directionless** [comment]
> > Remove the GRPC interface to this table
> 
> Does removing GRPC imply that we'll remove all the protobuf references as well? I'm not clear on how intertwined the 2 are. If so, the would it just be vanilla json?

We have protobuf interfaces? The jsonrpc ones, if they exist, should also go. I'm not actually sure any of them are still around, you'd need to dig around #390 and see what remains.

Basically, this is getting a lot simpler. 

All the GRPC is moribund, and can be ripped out. And we want a much simpler table that displays whatever is in the bbolt bucket. Some future thing will write to that bucket. 

I guess there's a slight wobble in that buckets are plain KV stores, and this should be an EAV table. But that's just data conversion
