### ISSUE TITLE
The debug logs should write to `debug.txt` 

### ISSUE THREAD

**Issue by directionless** [kolide/launcher#942]
Some of the support tools we use don't like the `.log` extension, but they work with `.txt`. And while I feel slightly weird making the debug logs write to `debug.txt`, we should be pragmatic, and roll with it.

We should update launcher to write to `debug.txt`, but the rotation code needs to handle both.

**Comment by FritzX6** [comment]
As an alternative could we write our launcher logs to JSON instead? This would also allow individuals to remotely collect logs from devices using the `kolide_json` table.

**Comment by RebeccaMahany** [comment]
Will require an update to https://help.kolide.com/en/articles/6338588-locating-logs-on-mac-windows-or-linux-devices before release

**Comment by directionless** [comment]
> As an alternative could we write our launcher logs to JSON instead? This would also allow teams to remotely collect logs from devices using the `kolide_json` table.

Not needed. The kolide_json table doesn't pay attention to file names. It'll read whatever and try to parse it as json.

Though think Becca opted to do that anyhow.

**Comment by directionless** [comment]
Fixed by #944
