### ISSUE TITLE
osquery worker doesn't restart plugin

### ISSUE THREAD

**Issue by groob** [kolide/launcher#95]
I think this is a bug. From the logs:

```
W0825 12:48:55.290359 106020864 watcher.cpp:286] osqueryd worker (60012): Memory limits exceeded: 209854464
E0825 12:49:09.147480 3033838528 init.cpp:568] Cannot activate kolide_grpc config plugin: Unknown registry plugin: kolide_grpc
```

Looks like the osqueryd worker was killed because of a memory limit, but it came back up without the extension? 
The launcher was running (launchd didn't restart it) but the activity stopped. 

Maybe we could do some sort of `select 1` query every x seconds? Or a custom healthz table?

**Comment by heywoodlh** [comment]
I will get more help on Slack. Thanks for the response!
