### ISSUE TITLE
Begin work on Autoupdate: The Next Generation 

### ISSUE THREAD

**Issue by directionless** [kolide/launcher#954]
I think it's finally time to revisit our autoupdate code! Excitement! Adventures! Bugs....

At a high level, I think our goals are:
* Remove Notary
* Use some modern libraries (Probably `go-tuf`, happy to hear other suggestions)
* Use a reasonable channel model for specifying which versions
* Expose more functionality inside launcher (right now it's all abstracted out into a goroutine that mostly does it's own thing)
* Improve testability / dev setups

I'd imagine some milestones like:
* [x] Play with go-tuf. What's it like running a server? A client? Can we _not_ have a server, and do it with a static set of files?
* [x] What would `porter` look like?
* [x] Launcher code? Proper channel and signaling usage
* [x] Test cases!
* [x] deploy a prod server
* [x] go!

launcher work remaining as of 29 June 2023:
* [x] Point to per-arch path https://github.com/kolide/launcher/pull/1195
* [x] Roll out new autoupdate code for internal testing on nightly -- https://github.com/kolide/launcher/pull/1391
* [x] Roll out new autoupdate code for internal testing on beta
* [x] Enable gradual rollout to stable (https://github.com/kolide/launcher/pull/1526)
* [x] Release autoupdate fully to stable

endpoint-releaser and monorepo work:
* [x] New TUF infrastructure for development
* [x] New TUF infrastructure for production
* [x] endpoint-releaser publishes and promotes releases to new TUF infrastructure
* [x] Monitor + alert when TUF keys are nearing expiration (https://github.com/kolide/endpoint-releaser/issues/71)
* [x] Allow for changing TUF passphrase (completed but no CI job)

**Comment by RebeccaMahany** [comment]
Blocks https://github.com/kolide/launcher/issues/896

**Comment by RebeccaMahany** [comment]
100% of devices now have the `use_tuf_autoupdater` feature flag set.

Planned improvements filed in https://github.com/kolide/launcher/issues/1577.
