### ISSUE TITLE
Launcher desktop needs a better default menu

### ISSUE THREAD

**Issue by seejdev** [kolide/launcher#995]
In the case that launcher can't successfully get the menu data from k2, we display a default static and hard-coded menu. Right now this menu is very simple and just displays the version of launcher. Once #988 is complete, we should replace this default menu with one that is a little more useful to the user.

Here is the function that needs to be updated: https://github.com/kolide/launcher/blob/main/ee/desktop/menu/menu.go#L122-L134

**Comment by directionless** [comment]
We'll get Fritz or Jason to weigh in.

**Comment by directionless** [comment]
I think we did this enough. At least, no one is complaining
